// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:22 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.Timeline
namespace UnityEngine::Timeline {
  // Autogenerated type: UnityEngine.Timeline.ClipCaps
  struct ClipCaps : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public UnityEngine.Timeline.ClipCaps None
    static constexpr const int None = 0;
    // Get static field: static public UnityEngine.Timeline.ClipCaps None
    static UnityEngine::Timeline::ClipCaps _get_None();
    // Set static field: static public UnityEngine.Timeline.ClipCaps None
    static void _set_None(UnityEngine::Timeline::ClipCaps value);
    // static field const value: static public UnityEngine.Timeline.ClipCaps Looping
    static constexpr const int Looping = 1;
    // Get static field: static public UnityEngine.Timeline.ClipCaps Looping
    static UnityEngine::Timeline::ClipCaps _get_Looping();
    // Set static field: static public UnityEngine.Timeline.ClipCaps Looping
    static void _set_Looping(UnityEngine::Timeline::ClipCaps value);
    // static field const value: static public UnityEngine.Timeline.ClipCaps Extrapolation
    static constexpr const int Extrapolation = 2;
    // Get static field: static public UnityEngine.Timeline.ClipCaps Extrapolation
    static UnityEngine::Timeline::ClipCaps _get_Extrapolation();
    // Set static field: static public UnityEngine.Timeline.ClipCaps Extrapolation
    static void _set_Extrapolation(UnityEngine::Timeline::ClipCaps value);
    // static field const value: static public UnityEngine.Timeline.ClipCaps ClipIn
    static constexpr const int ClipIn = 4;
    // Get static field: static public UnityEngine.Timeline.ClipCaps ClipIn
    static UnityEngine::Timeline::ClipCaps _get_ClipIn();
    // Set static field: static public UnityEngine.Timeline.ClipCaps ClipIn
    static void _set_ClipIn(UnityEngine::Timeline::ClipCaps value);
    // static field const value: static public UnityEngine.Timeline.ClipCaps SpeedMultiplier
    static constexpr const int SpeedMultiplier = 8;
    // Get static field: static public UnityEngine.Timeline.ClipCaps SpeedMultiplier
    static UnityEngine::Timeline::ClipCaps _get_SpeedMultiplier();
    // Set static field: static public UnityEngine.Timeline.ClipCaps SpeedMultiplier
    static void _set_SpeedMultiplier(UnityEngine::Timeline::ClipCaps value);
    // static field const value: static public UnityEngine.Timeline.ClipCaps Blending
    static constexpr const int Blending = 16;
    // Get static field: static public UnityEngine.Timeline.ClipCaps Blending
    static UnityEngine::Timeline::ClipCaps _get_Blending();
    // Set static field: static public UnityEngine.Timeline.ClipCaps Blending
    static void _set_Blending(UnityEngine::Timeline::ClipCaps value);
    // static field const value: static public UnityEngine.Timeline.ClipCaps All
    static constexpr const int All = -1;
    // Get static field: static public UnityEngine.Timeline.ClipCaps All
    static UnityEngine::Timeline::ClipCaps _get_All();
    // Set static field: static public UnityEngine.Timeline.ClipCaps All
    static void _set_All(UnityEngine::Timeline::ClipCaps value);
    // Creating value type constructor for type: ClipCaps
    ClipCaps(int value_ = {}) : value{value_} {}
  }; // UnityEngine.Timeline.ClipCaps
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::Timeline::ClipCaps, "UnityEngine.Timeline", "ClipCaps");
#pragma pack(pop)
