// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:21 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: UnityEngine.Timeline.TimelineAsset
#include "UnityEngine/Timeline/TimelineAsset.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.Timeline
namespace UnityEngine::Timeline {
  // Autogenerated type: UnityEngine.Timeline.TimelineAsset/TimelineAssetUpgrade
  class TimelineAsset::TimelineAssetUpgrade : public ::Il2CppObject {
  }; // UnityEngine.Timeline.TimelineAsset/TimelineAssetUpgrade
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::Timeline::TimelineAsset::TimelineAssetUpgrade*, "UnityEngine.Timeline", "TimelineAsset/TimelineAssetUpgrade");
#pragma pack(pop)
