// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:46 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: NUnit.Framework.Internal
namespace NUnit::Framework::Internal {
  // Autogenerated type: NUnit.Framework.Internal.StringUtil
  class StringUtil : public ::Il2CppObject {
    public:
    // static public System.Int32 Compare(System.String strA, System.String strB, System.Boolean ignoreCase)
    // Offset: 0x18D7890
    static int Compare(::Il2CppString* strA, ::Il2CppString* strB, bool ignoreCase);
    // static public System.Boolean StringsEqual(System.String strA, System.String strB, System.Boolean ignoreCase)
    // Offset: 0x18D789C
    static bool StringsEqual(::Il2CppString* strA, ::Il2CppString* strB, bool ignoreCase);
  }; // NUnit.Framework.Internal.StringUtil
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Framework::Internal::StringUtil*, "NUnit.Framework.Internal", "StringUtil");
#pragma pack(pop)
