// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:14 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Configuration.ConfigurationElement
#include "System/Configuration/ConfigurationElement.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Net.Configuration
namespace System::Net::Configuration {
  // Autogenerated type: System.Net.Configuration.BypassElement
  class BypassElement : public System::Configuration::ConfigurationElement {
  }; // System.Net.Configuration.BypassElement
}
DEFINE_IL2CPP_ARG_TYPE(System::Net::Configuration::BypassElement*, "System.Net.Configuration", "BypassElement");
#pragma pack(pop)
