// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:14 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Configuration.ConfigurationElementCollection
#include "System/Configuration/ConfigurationElementCollection.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Net.Configuration
namespace System::Net::Configuration {
  // Autogenerated type: System.Net.Configuration.BypassElementCollection
  class BypassElementCollection : public System::Configuration::ConfigurationElementCollection {
    public:
    // public System.Void .ctor()
    // Offset: 0xF54D98
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static BypassElementCollection* New_ctor();
  }; // System.Net.Configuration.BypassElementCollection
}
DEFINE_IL2CPP_ARG_TYPE(System::Net::Configuration::BypassElementCollection*, "System.Net.Configuration", "BypassElementCollection");
#pragma pack(pop)
