// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:38 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Runtime.Remoting.Channels
namespace System::Runtime::Remoting::Channels {
  // Autogenerated type: System.Runtime.Remoting.Channels.IChannel
  class IChannel {
    public:
    // public System.String get_ChannelName()
    // Offset: 0xFFFFFFFF
    ::Il2CppString* get_ChannelName();
    // public System.Int32 get_ChannelPriority()
    // Offset: 0xFFFFFFFF
    int get_ChannelPriority();
  }; // System.Runtime.Remoting.Channels.IChannel
}
DEFINE_IL2CPP_ARG_TYPE(System::Runtime::Remoting::Channels::IChannel*, "System.Runtime.Remoting.Channels", "IChannel");
#pragma pack(pop)
