// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:21 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: TMPro.SpriteAssetUtilities
namespace TMPro::SpriteAssetUtilities {
  // Autogenerated type: TMPro.SpriteAssetUtilities.SpriteAssetImportFormats
  struct SpriteAssetImportFormats : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public TMPro.SpriteAssetUtilities.SpriteAssetImportFormats None
    static constexpr const int None = 0;
    // Get static field: static public TMPro.SpriteAssetUtilities.SpriteAssetImportFormats None
    static TMPro::SpriteAssetUtilities::SpriteAssetImportFormats _get_None();
    // Set static field: static public TMPro.SpriteAssetUtilities.SpriteAssetImportFormats None
    static void _set_None(TMPro::SpriteAssetUtilities::SpriteAssetImportFormats value);
    // static field const value: static public TMPro.SpriteAssetUtilities.SpriteAssetImportFormats TexturePacker
    static constexpr const int TexturePacker = 1;
    // Get static field: static public TMPro.SpriteAssetUtilities.SpriteAssetImportFormats TexturePacker
    static TMPro::SpriteAssetUtilities::SpriteAssetImportFormats _get_TexturePacker();
    // Set static field: static public TMPro.SpriteAssetUtilities.SpriteAssetImportFormats TexturePacker
    static void _set_TexturePacker(TMPro::SpriteAssetUtilities::SpriteAssetImportFormats value);
    // Creating value type constructor for type: SpriteAssetImportFormats
    SpriteAssetImportFormats(int value_ = {}) : value{value_} {}
  }; // TMPro.SpriteAssetUtilities.SpriteAssetImportFormats
}
DEFINE_IL2CPP_ARG_TYPE(TMPro::SpriteAssetUtilities::SpriteAssetImportFormats, "TMPro.SpriteAssetUtilities", "SpriteAssetImportFormats");
#pragma pack(pop)
