// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:15 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Xml
namespace System::Xml {
  // Autogenerated type: System.Xml.NamespaceHandling
  struct NamespaceHandling : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public System.Xml.NamespaceHandling Default
    static constexpr const int Default = 0;
    // Get static field: static public System.Xml.NamespaceHandling Default
    static System::Xml::NamespaceHandling _get_Default();
    // Set static field: static public System.Xml.NamespaceHandling Default
    static void _set_Default(System::Xml::NamespaceHandling value);
    // static field const value: static public System.Xml.NamespaceHandling OmitDuplicates
    static constexpr const int OmitDuplicates = 1;
    // Get static field: static public System.Xml.NamespaceHandling OmitDuplicates
    static System::Xml::NamespaceHandling _get_OmitDuplicates();
    // Set static field: static public System.Xml.NamespaceHandling OmitDuplicates
    static void _set_OmitDuplicates(System::Xml::NamespaceHandling value);
    // Creating value type constructor for type: NamespaceHandling
    NamespaceHandling(int value_ = {}) : value{value_} {}
  }; // System.Xml.NamespaceHandling
}
DEFINE_IL2CPP_ARG_TYPE(System::Xml::NamespaceHandling, "System.Xml", "NamespaceHandling");
#pragma pack(pop)
