// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:40 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Runtime.CompilerServices
namespace System::Runtime::CompilerServices {
  // Autogenerated type: System.Runtime.CompilerServices.IsVolatile
  class IsVolatile : public ::Il2CppObject {
  }; // System.Runtime.CompilerServices.IsVolatile
}
DEFINE_IL2CPP_ARG_TYPE(System::Runtime::CompilerServices::IsVolatile*, "System.Runtime.CompilerServices", "IsVolatile");
#pragma pack(pop)
