// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:37 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Collections
namespace System::Collections {
  // Forward declaring type: IEnumerator
  class IEnumerator;
}
// Completed forward declares
// Type namespace: UnityEngine.TestTools
namespace UnityEngine::TestTools {
  // Autogenerated type: UnityEngine.TestTools.TestCommandPcHelper
  class TestCommandPcHelper : public ::Il2CppObject {
    public:
    // public System.Void SetEnumeratorPC(System.Collections.IEnumerator enumerator, System.Int32 pc)
    // Offset: 0xE2D0B8
    void SetEnumeratorPC(System::Collections::IEnumerator* enumerator, int pc);
    // public System.Int32 GetEnumeratorPC(System.Collections.IEnumerator enumerator)
    // Offset: 0xE2D0BC
    int GetEnumeratorPC(System::Collections::IEnumerator* enumerator);
    // public System.Void .ctor()
    // Offset: 0xE2D0C4
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static TestCommandPcHelper* New_ctor();
  }; // UnityEngine.TestTools.TestCommandPcHelper
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::TestTools::TestCommandPcHelper*, "UnityEngine.TestTools", "TestCommandPcHelper");
#pragma pack(pop)
