// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:36 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: NUnit.Framework.NUnitAttribute
#include "NUnit/Framework/NUnitAttribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.TestTools
namespace UnityEngine::TestTools {
  // Autogenerated type: UnityEngine.TestTools.UnitySetUpAttribute
  class UnitySetUpAttribute : public NUnit::Framework::NUnitAttribute {
  }; // UnityEngine.TestTools.UnitySetUpAttribute
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::TestTools::UnitySetUpAttribute*, "UnityEngine.TestTools", "UnitySetUpAttribute");
#pragma pack(pop)
