// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:31 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: UnityEngine.PlayerLoop.PostLateUpdate
#include "UnityEngine/PlayerLoop/PostLateUpdate.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.PlayerLoop
namespace UnityEngine::PlayerLoop {
  // Autogenerated type: UnityEngine.PlayerLoop.PostLateUpdate/ResetInputAxis
  struct PostLateUpdate::ResetInputAxis : public System::ValueType {
    // Creating value type constructor for type: ResetInputAxis
    ResetInputAxis() {}
  }; // UnityEngine.PlayerLoop.PostLateUpdate/ResetInputAxis
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::PlayerLoop::PostLateUpdate::ResetInputAxis, "UnityEngine.PlayerLoop", "PostLateUpdate/ResetInputAxis");
#pragma pack(pop)
