// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:30 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: UnityEngine.PlayerLoop.PreLateUpdate
#include "UnityEngine/PlayerLoop/PreLateUpdate.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.PlayerLoop
namespace UnityEngine::PlayerLoop {
  // Autogenerated type: UnityEngine.PlayerLoop.PreLateUpdate/DirectorUpdateAnimationEnd
  struct PreLateUpdate::DirectorUpdateAnimationEnd : public System::ValueType {
    // Creating value type constructor for type: DirectorUpdateAnimationEnd
    DirectorUpdateAnimationEnd() {}
  }; // UnityEngine.PlayerLoop.PreLateUpdate/DirectorUpdateAnimationEnd
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::PlayerLoop::PreLateUpdate::DirectorUpdateAnimationEnd, "UnityEngine.PlayerLoop", "PreLateUpdate/DirectorUpdateAnimationEnd");
#pragma pack(pop)
