// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:18 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: UnityEngine::ProBuilder::Poly2Tri
namespace UnityEngine::ProBuilder::Poly2Tri {
  // Forward declaring type: AdvancingFrontNode
  class AdvancingFrontNode;
}
// Completed forward declares
// Type namespace: UnityEngine.ProBuilder.Poly2Tri
namespace UnityEngine::ProBuilder::Poly2Tri {
  // Autogenerated type: UnityEngine.ProBuilder.Poly2Tri.DTSweepBasin
  class DTSweepBasin : public ::Il2CppObject {
    public:
    // public UnityEngine.ProBuilder.Poly2Tri.AdvancingFrontNode leftNode
    // Offset: 0x10
    UnityEngine::ProBuilder::Poly2Tri::AdvancingFrontNode* leftNode;
    // public UnityEngine.ProBuilder.Poly2Tri.AdvancingFrontNode bottomNode
    // Offset: 0x18
    UnityEngine::ProBuilder::Poly2Tri::AdvancingFrontNode* bottomNode;
    // public UnityEngine.ProBuilder.Poly2Tri.AdvancingFrontNode rightNode
    // Offset: 0x20
    UnityEngine::ProBuilder::Poly2Tri::AdvancingFrontNode* rightNode;
    // public System.Double width
    // Offset: 0x28
    double width;
    // public System.Boolean leftHighest
    // Offset: 0x30
    bool leftHighest;
    // public System.Void .ctor()
    // Offset: 0x19169DC
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static DTSweepBasin* New_ctor();
  }; // UnityEngine.ProBuilder.Poly2Tri.DTSweepBasin
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::ProBuilder::Poly2Tri::DTSweepBasin*, "UnityEngine.ProBuilder.Poly2Tri", "DTSweepBasin");
#pragma pack(pop)
