// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:18 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.ProBuilder.Poly2Tri.TriangulationPoint
#include "UnityEngine/ProBuilder/Poly2Tri/TriangulationPoint.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.ProBuilder.Poly2Tri
namespace UnityEngine::ProBuilder::Poly2Tri {
  // Autogenerated type: UnityEngine.ProBuilder.Poly2Tri.PolygonPoint
  class PolygonPoint : public UnityEngine::ProBuilder::Poly2Tri::TriangulationPoint {
    public:
    // public System.Void .ctor(System.Double x, System.Double y, System.Int32 index)
    // Offset: 0x1918B38
    // Implemented from: UnityEngine.ProBuilder.Poly2Tri.TriangulationPoint
    // Base method: System.Void TriangulationPoint::.ctor(System.Double x, System.Double y, System.Int32 index)
    static PolygonPoint* New_ctor(double x, double y, int index);
  }; // UnityEngine.ProBuilder.Poly2Tri.PolygonPoint
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::ProBuilder::Poly2Tri::PolygonPoint*, "UnityEngine.ProBuilder.Poly2Tri", "PolygonPoint");
#pragma pack(pop)
