// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:45 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: NUnit.Framework.Interfaces
namespace NUnit::Framework::Interfaces {
  // Autogenerated type: NUnit.Framework.Interfaces.IImplyFixture
  class IImplyFixture {
  }; // NUnit.Framework.Interfaces.IImplyFixture
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Framework::Interfaces::IImplyFixture*, "NUnit.Framework.Interfaces", "IImplyFixture");
#pragma pack(pop)
