// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:47 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: NUnit.Framework.Interfaces.ICommandWrapper
#include "NUnit/Framework/Interfaces/ICommandWrapper.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: NUnit.Framework.Interfaces
namespace NUnit::Framework::Interfaces {
  // Autogenerated type: NUnit.Framework.Interfaces.IWrapTestMethod
  class IWrapTestMethod : public NUnit::Framework::Interfaces::ICommandWrapper {
  }; // NUnit.Framework.Interfaces.IWrapTestMethod
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Framework::Interfaces::IWrapTestMethod*, "NUnit.Framework.Interfaces", "IWrapTestMethod");
#pragma pack(pop)
