// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:07 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: PersistentScriptableObject
#include "GlobalNamespace/PersistentScriptableObject.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: AchievementSO
  class AchievementSO : public GlobalNamespace::PersistentScriptableObject {
    public:
    // private System.String _achievementId
    // Offset: 0x18
    ::Il2CppString* achievementId;
    // public System.String get_achievementId()
    // Offset: 0x1967EF0
    ::Il2CppString* get_achievementId();
    // public System.Void .ctor()
    // Offset: 0x1967EF8
    // Implemented from: PersistentScriptableObject
    // Base method: System.Void PersistentScriptableObject::.ctor()
    // Base method: System.Void ScriptableObject::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    static AchievementSO* New_ctor();
  }; // AchievementSO
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::AchievementSO*, "", "AchievementSO");
#pragma pack(pop)
