// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:01 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: AudioHelpers
  class AudioHelpers : public ::Il2CppObject {
    public:
    // static public System.Single NormalizedVolumeToDB(System.Single normalizedVolume)
    // Offset: 0xC97E58
    static float NormalizedVolumeToDB(float normalizedVolume);
  }; // AudioHelpers
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::AudioHelpers*, "", "AudioHelpers");
#pragma pack(pop)
