// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:10 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: GlobalNamespace
namespace GlobalNamespace {
  // Forward declaring type: IDifficultyBeatmapSet
  class IDifficultyBeatmapSet;
  // Forward declaring type: PreviewDifficultyBeatmapSet
  class PreviewDifficultyBeatmapSet;
}
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: DifficultyBeatmapSetExtensions
  class DifficultyBeatmapSetExtensions : public ::Il2CppObject {
    public:
    // static public T[] GetDifficultyBeatmapSetsWithout360Movement(T[] difficultyBeatmapSets)
    // Offset: 0xD43894
    template<class T>
    static ::Array<T>* GetDifficultyBeatmapSetsWithout360Movement(::Array<T>* difficultyBeatmapSets) {
      static_assert(std::is_convertible_v<T, GlobalNamespace::IDifficultyBeatmapSet*>);
      return CRASH_UNLESS(il2cpp_utils::RunGenericMethod<::Array<T>*>("", "DifficultyBeatmapSetExtensions", "GetDifficultyBeatmapSetsWithout360Movement", {il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<T>::get()}, difficultyBeatmapSets));
    }
    // static public PreviewDifficultyBeatmapSet[] GetPreviewDifficultyBeatmapSets(T[] difficultyBeatmapSets)
    // Offset: 0x14C8448
    template<class T>
    static ::Array<GlobalNamespace::PreviewDifficultyBeatmapSet*>* GetPreviewDifficultyBeatmapSets(::Array<T>* difficultyBeatmapSets) {
      static_assert(std::is_convertible_v<T, GlobalNamespace::IDifficultyBeatmapSet*>);
      return CRASH_UNLESS(il2cpp_utils::RunGenericMethod<::Array<GlobalNamespace::PreviewDifficultyBeatmapSet*>*>("", "DifficultyBeatmapSetExtensions", "GetPreviewDifficultyBeatmapSets", {il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<T>::get()}, difficultyBeatmapSets));
    }
  }; // DifficultyBeatmapSetExtensions
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::DifficultyBeatmapSetExtensions*, "", "DifficultyBeatmapSetExtensions");
#pragma pack(pop)
