// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:19 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: EulaViewController
#include "GlobalNamespace/EulaViewController.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: EulaViewController/InitData
  class EulaViewController::InitData : public ::Il2CppObject {
    public:
    // public readonly System.Boolean showDoNotAgreeButton
    // Offset: 0x10
    bool showDoNotAgreeButton;
    // public System.Void .ctor(System.Boolean showDoNotAgreeButton)
    // Offset: 0xBD6714
    static EulaViewController::InitData* New_ctor(bool showDoNotAgreeButton);
  }; // EulaViewController/InitData
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::EulaViewController::InitData*, "", "EulaViewController/InitData");
#pragma pack(pop)
