// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:21 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: SceneSetupData
#include "GlobalNamespace/SceneSetupData.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: GlobalNamespace
namespace GlobalNamespace {
  // Forward declaring type: ColorScheme
  class ColorScheme;
}
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: GameCoreSceneSetupData
  class GameCoreSceneSetupData : public GlobalNamespace::SceneSetupData {
    public:
    // private ColorScheme <colorScheme>k__BackingField
    // Offset: 0x10
    GlobalNamespace::ColorScheme* colorScheme;
    // public ColorScheme get_colorScheme()
    // Offset: 0xBDDD3C
    GlobalNamespace::ColorScheme* get_colorScheme();
    // private System.Void set_colorScheme(ColorScheme value)
    // Offset: 0xBDDD44
    void set_colorScheme(GlobalNamespace::ColorScheme* value);
    // public System.Void .ctor(ColorScheme colorScheme)
    // Offset: 0xBDDD4C
    static GameCoreSceneSetupData* New_ctor(GlobalNamespace::ColorScheme* colorScheme);
  }; // GameCoreSceneSetupData
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::GameCoreSceneSetupData*, "", "GameCoreSceneSetupData");
#pragma pack(pop)
