// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:01 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.MonoBehaviour
#include "UnityEngine/MonoBehaviour.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: HorizontalCameraFov
  class HorizontalCameraFov : public UnityEngine::MonoBehaviour {
    public:
    // public System.Single _horizontalFOV
    // Offset: 0x18
    float horizontalFOV;
    // protected System.Void Awake()
    // Offset: 0xCA1B04
    void Awake();
    // public System.Void .ctor()
    // Offset: 0xCA1BF0
    // Implemented from: UnityEngine.MonoBehaviour
    // Base method: System.Void MonoBehaviour::.ctor()
    // Base method: System.Void Behaviour::.ctor()
    // Base method: System.Void Component::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    static HorizontalCameraFov* New_ctor();
  }; // HorizontalCameraFov
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::HorizontalCameraFov*, "", "HorizontalCameraFov");
#pragma pack(pop)
