// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:09 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: IAnnotatedBeatmapLevelCollection
#include "GlobalNamespace/IAnnotatedBeatmapLevelCollection.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: IBeatmapLevelPack
  class IBeatmapLevelPack : public GlobalNamespace::IAnnotatedBeatmapLevelCollection {
    public:
    // public System.String get_packID()
    // Offset: 0xFFFFFFFF
    ::Il2CppString* get_packID();
    // public System.String get_packName()
    // Offset: 0xFFFFFFFF
    ::Il2CppString* get_packName();
    // public System.String get_shortPackName()
    // Offset: 0xFFFFFFFF
    ::Il2CppString* get_shortPackName();
  }; // IBeatmapLevelPack
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::IBeatmapLevelPack*, "", "IBeatmapLevelPack");
#pragma pack(pop)
