// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:03 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: InstancingValuesTester
#include "GlobalNamespace/InstancingValuesTester.hpp"
// Including type: UnityEngine.Color
#include "UnityEngine/Color.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: InstancingValuesTester/PropertyNameColorValuePair
  class InstancingValuesTester::PropertyNameColorValuePair : public ::Il2CppObject {
    public:
    // public System.String propertyName
    // Offset: 0x10
    ::Il2CppString* propertyName;
    // public UnityEngine.Color color
    // Offset: 0x18
    UnityEngine::Color color;
    // public System.Void .ctor()
    // Offset: 0x1810BA0
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static InstancingValuesTester::PropertyNameColorValuePair* New_ctor();
  }; // InstancingValuesTester/PropertyNameColorValuePair
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::InstancingValuesTester::PropertyNameColorValuePair*, "", "InstancingValuesTester/PropertyNameColorValuePair");
#pragma pack(pop)
