// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:20 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: LevelFilteringNavigationController
#include "GlobalNamespace/LevelFilteringNavigationController.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Action
  class Action;
}
// Forward declaring namespace: GlobalNamespace
namespace GlobalNamespace {
  // Forward declaring type: IAnnotatedBeatmapLevelCollection
  class IAnnotatedBeatmapLevelCollection;
}
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: LevelFilteringNavigationController/TabBarData
  class LevelFilteringNavigationController::TabBarData : public ::Il2CppObject {
    public:
    // public System.String tabBarTitle
    // Offset: 0x10
    ::Il2CppString* tabBarTitle;
    // public System.Action action
    // Offset: 0x18
    System::Action* action;
    // public System.Int32 selectedItem
    // Offset: 0x20
    int selectedItem;
    // public IAnnotatedBeatmapLevelCollection[] annotatedBeatmapLevelCollections
    // Offset: 0x28
    ::Array<GlobalNamespace::IAnnotatedBeatmapLevelCollection*>* annotatedBeatmapLevelCollections;
    // public IAnnotatedBeatmapLevelCollection get_selectedAnnotatedBeatmapLevelCollections()
    // Offset: 0xB4C714
    GlobalNamespace::IAnnotatedBeatmapLevelCollection* get_selectedAnnotatedBeatmapLevelCollections();
    // public System.Void .ctor()
    // Offset: 0xB4C438
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static LevelFilteringNavigationController::TabBarData* New_ctor();
  }; // LevelFilteringNavigationController/TabBarData
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::LevelFilteringNavigationController::TabBarData*, "", "LevelFilteringNavigationController/TabBarData");
#pragma pack(pop)
