// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:01 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: ManualUpdate
  class ManualUpdate : public ::Il2CppObject {
    public:
    // public System.Void .ctor()
    // Offset: 0xCA2A70
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static ManualUpdate* New_ctor();
  }; // ManualUpdate
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::ManualUpdate*, "", "ManualUpdate");
#pragma pack(pop)
