// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:22 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: ScenesTransitionSetupDataSO
#include "GlobalNamespace/ScenesTransitionSetupDataSO.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: GlobalNamespace
namespace GlobalNamespace {
  // Forward declaring type: SceneInfo
  class SceneInfo;
}
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: MenuScenesTransitionSetupDataSO
  class MenuScenesTransitionSetupDataSO : public GlobalNamespace::ScenesTransitionSetupDataSO {
    public:
    // private SceneInfo _menuSceneInfo
    // Offset: 0x28
    GlobalNamespace::SceneInfo* menuSceneInfo;
    // private SceneInfo _menuCoreSceneInfo
    // Offset: 0x30
    GlobalNamespace::SceneInfo* menuCoreSceneInfo;
    // private SceneInfo _menuEnvironmentSceneInfo
    // Offset: 0x38
    GlobalNamespace::SceneInfo* menuEnvironmentSceneInfo;
    // private SceneInfo _menuViewControllersSceneInfo
    // Offset: 0x40
    GlobalNamespace::SceneInfo* menuViewControllersSceneInfo;
    // public System.Void Init()
    // Offset: 0xBED1F8
    void Init();
    // public System.Void .ctor()
    // Offset: 0xBED364
    // Implemented from: ScenesTransitionSetupDataSO
    // Base method: System.Void ScenesTransitionSetupDataSO::.ctor()
    // Base method: System.Void PersistentScriptableObject::.ctor()
    // Base method: System.Void ScriptableObject::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    static MenuScenesTransitionSetupDataSO* New_ctor();
  }; // MenuScenesTransitionSetupDataSO
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::MenuScenesTransitionSetupDataSO*, "", "MenuScenesTransitionSetupDataSO");
#pragma pack(pop)
