// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:50 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: OVRPlugin
#include "GlobalNamespace/OVRPlugin.hpp"
// Including type: OVRPlugin/BoneId
#include "GlobalNamespace/OVRPlugin_BoneId.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: OVRPlugin/Bone
  struct OVRPlugin::Bone : public System::ValueType {
    public:
    // public OVRPlugin/BoneId Id
    // Offset: 0x0
    GlobalNamespace::OVRPlugin::BoneId Id;
    // public System.Int16 ParentBoneIndex
    // Offset: 0x4
    int16_t ParentBoneIndex;
    // public OVRPlugin/Posef Pose
    // Offset: 0x8
    GlobalNamespace::OVRPlugin::Posef Pose;
    // Creating value type constructor for type: Bone
    Bone(GlobalNamespace::OVRPlugin::BoneId Id_ = {}, int16_t ParentBoneIndex_ = {}, GlobalNamespace::OVRPlugin::Posef Pose_ = {}) : Id{Id_}, ParentBoneIndex{ParentBoneIndex_}, Pose{Pose_} {}
  }; // OVRPlugin/Bone
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::OVRPlugin::Bone, "", "OVRPlugin/Bone");
#pragma pack(pop)
