// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:52 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: OVRSkeletonRenderer
#include "GlobalNamespace/OVRSkeletonRenderer.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: OVRSkeletonRenderer/IOVRSkeletonRendererDataProvider
  class OVRSkeletonRenderer::IOVRSkeletonRendererDataProvider {
    public:
    // public OVRSkeletonRenderer/SkeletonRendererData GetSkeletonRendererData()
    // Offset: 0xFFFFFFFF
    GlobalNamespace::OVRSkeletonRenderer::SkeletonRendererData GlobalNamespace_OVRSkeletonRenderer_IOVRSkeletonRendererDataProvider_GetSkeletonRendererData();
  }; // OVRSkeletonRenderer/IOVRSkeletonRendererDataProvider
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::OVRSkeletonRenderer::IOVRSkeletonRendererDataProvider*, "", "OVRSkeletonRenderer/IOVRSkeletonRendererDataProvider");
#pragma pack(pop)
