// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:11 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
// Including type: PlatformUserModelSO
#include "GlobalNamespace/PlatformUserModelSO.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: PlatformUserModelSO/GetUserNamesForUserIdsResult
  struct PlatformUserModelSO::GetUserNamesForUserIdsResult : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public PlatformUserModelSO/GetUserNamesForUserIdsResult OK
    static constexpr const int OK = 0;
    // Get static field: static public PlatformUserModelSO/GetUserNamesForUserIdsResult OK
    static GlobalNamespace::PlatformUserModelSO::GetUserNamesForUserIdsResult _get_OK();
    // Set static field: static public PlatformUserModelSO/GetUserNamesForUserIdsResult OK
    static void _set_OK(GlobalNamespace::PlatformUserModelSO::GetUserNamesForUserIdsResult value);
    // static field const value: static public PlatformUserModelSO/GetUserNamesForUserIdsResult Failed
    static constexpr const int Failed = 1;
    // Get static field: static public PlatformUserModelSO/GetUserNamesForUserIdsResult Failed
    static GlobalNamespace::PlatformUserModelSO::GetUserNamesForUserIdsResult _get_Failed();
    // Set static field: static public PlatformUserModelSO/GetUserNamesForUserIdsResult Failed
    static void _set_Failed(GlobalNamespace::PlatformUserModelSO::GetUserNamesForUserIdsResult value);
    // Creating value type constructor for type: GetUserNamesForUserIdsResult
    GetUserNamesForUserIdsResult(int value_ = {}) : value{value_} {}
  }; // PlatformUserModelSO/GetUserNamesForUserIdsResult
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::PlatformUserModelSO::GetUserNamesForUserIdsResult, "", "PlatformUserModelSO/GetUserNamesForUserIdsResult");
#pragma pack(pop)
