// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:04 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.MonoBehaviour
#include "UnityEngine/MonoBehaviour.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: UnityEngine
namespace UnityEngine {
  // Forward declaring type: RenderTexture
  class RenderTexture;
  // Forward declaring type: Camera
  class Camera;
}
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: RenderTextureFromPostEffect
  class RenderTextureFromPostEffect : public UnityEngine::MonoBehaviour {
    public:
    // public UnityEngine.RenderTexture _targetTexture
    // Offset: 0x18
    UnityEngine::RenderTexture* targetTexture;
    // private UnityEngine.Camera _camera
    // Offset: 0x20
    UnityEngine::Camera* camera;
    // public UnityEngine.RenderTexture get_targetTexture()
    // Offset: 0x18FAD5C
    UnityEngine::RenderTexture* get_targetTexture();
    // protected System.Void Awake()
    // Offset: 0x18FAD64
    void Awake();
    // private System.Void OnRenderImage(UnityEngine.RenderTexture src, UnityEngine.RenderTexture dst)
    // Offset: 0x18FADC4
    void OnRenderImage(UnityEngine::RenderTexture* src, UnityEngine::RenderTexture* dst);
    // public System.Void .ctor()
    // Offset: 0x18FAFE8
    // Implemented from: UnityEngine.MonoBehaviour
    // Base method: System.Void MonoBehaviour::.ctor()
    // Base method: System.Void Behaviour::.ctor()
    // Base method: System.Void Component::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    static RenderTextureFromPostEffect* New_ctor();
  }; // RenderTextureFromPostEffect
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::RenderTextureFromPostEffect*, "", "RenderTextureFromPostEffect");
#pragma pack(pop)
