// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:22 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: SceneSetupData
#include "GlobalNamespace/SceneSetupData.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: StandardGameplaySceneSetupData
  class StandardGameplaySceneSetupData : public GlobalNamespace::SceneSetupData {
    public:
    // public readonly System.Boolean autoRestart
    // Offset: 0x10
    bool autoRestart;
    // public readonly System.String songName
    // Offset: 0x18
    ::Il2CppString* songName;
    // public readonly System.String songSubName
    // Offset: 0x20
    ::Il2CppString* songSubName;
    // public readonly System.String difficultyName
    // Offset: 0x28
    ::Il2CppString* difficultyName;
    // public readonly System.String backButtonText
    // Offset: 0x30
    ::Il2CppString* backButtonText;
    // public System.Void .ctor(System.Boolean autoRestart, System.String songName, System.String songSubName, System.String difficultyName, System.String backButtonText)
    // Offset: 0xB881C8
    static StandardGameplaySceneSetupData* New_ctor(bool autoRestart, ::Il2CppString* songName, ::Il2CppString* songSubName, ::Il2CppString* difficultyName, ::Il2CppString* backButtonText);
  }; // StandardGameplaySceneSetupData
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::StandardGameplaySceneSetupData*, "", "StandardGameplaySceneSetupData");
#pragma pack(pop)
