// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:06 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.MonoBehaviour
#include "UnityEngine/MonoBehaviour.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: SteamInit
  class SteamInit : public UnityEngine::MonoBehaviour {
    public:
    // public System.Void Init()
    // Offset: 0xB90908
    void Init();
    // public System.Void .ctor()
    // Offset: 0xB9090C
    // Implemented from: UnityEngine.MonoBehaviour
    // Base method: System.Void MonoBehaviour::.ctor()
    // Base method: System.Void Behaviour::.ctor()
    // Base method: System.Void Component::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    static SteamInit* New_ctor();
  }; // SteamInit
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::SteamInit*, "", "SteamInit");
#pragma pack(pop)
