// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:05 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: SteamVR_Events
#include "GlobalNamespace/SteamVR_Events.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: SteamVR_Events/Action
  class SteamVR_Events::Action : public ::Il2CppObject {
    public:
    // public System.Void Enable(System.Boolean enabled)
    // Offset: 0xFFFFFFFF
    void Enable(bool enabled);
    // public System.Void set_enabled(System.Boolean value)
    // Offset: 0xD6AB44
    void set_enabled(bool value);
    // protected System.Void .ctor()
    // Offset: 0xD6C48C
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static SteamVR_Events::Action* New_ctor();
  }; // SteamVR_Events/Action
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::SteamVR_Events::Action*, "", "SteamVR_Events/Action");
#pragma pack(pop)
