// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:13 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: VersionSaveData
  class VersionSaveData : public ::Il2CppObject {
    public:
    // public System.String version
    // Offset: 0x10
    ::Il2CppString* version;
    // public System.Void .ctor()
    // Offset: 0xC40D98
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static VersionSaveData* New_ctor();
  }; // VersionSaveData
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::VersionSaveData*, "", "VersionSaveData");
#pragma pack(pop)
