// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:03 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: OVRPlugin
#include "GlobalNamespace/OVRPlugin.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: UnityEngine::XR
namespace UnityEngine::XR {
  // Forward declaring type: XRNode
  struct XRNode;
}
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: XRNodeExtensions
  class XRNodeExtensions : public ::Il2CppObject {
    public:
    // static public OVRPlugin/Node OculusNode(UnityEngine.XR.XRNode node)
    // Offset: 0xCAA7A8
    static GlobalNamespace::OVRPlugin::Node OculusNode(UnityEngine::XR::XRNode node);
    // static public System.Int32 PSMoveDeviceIndex(UnityEngine.XR.XRNode node)
    // Offset: 0xCAAD54
    static int PSMoveDeviceIndex(UnityEngine::XR::XRNode node);
  }; // XRNodeExtensions
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::XRNodeExtensions*, "", "XRNodeExtensions");
#pragma pack(pop)
