// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:00 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.MonoBehaviour
#include "UnityEngine/MonoBehaviour.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: RootMotion::FinalIK
namespace RootMotion::FinalIK {
  // Forward declaring type: IK
  class IK;
}
// Completed forward declares
// Type namespace: RootMotion.FinalIK
namespace RootMotion::FinalIK {
  // Autogenerated type: RootMotion.FinalIK.EditorIK
  class EditorIK : public UnityEngine::MonoBehaviour {
    public:
    // private RootMotion.FinalIK.IK ik
    // Offset: 0x18
    RootMotion::FinalIK::IK* ik;
    // private System.Void Start()
    // Offset: 0x1395670
    void Start();
    // private System.Void Update()
    // Offset: 0x1395718
    void Update();
    // public System.Void .ctor()
    // Offset: 0x13957E8
    // Implemented from: UnityEngine.MonoBehaviour
    // Base method: System.Void MonoBehaviour::.ctor()
    // Base method: System.Void Behaviour::.ctor()
    // Base method: System.Void Component::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    static EditorIK* New_ctor();
  }; // RootMotion.FinalIK.EditorIK
}
DEFINE_IL2CPP_ARG_TYPE(RootMotion::FinalIK::EditorIK*, "RootMotion.FinalIK", "EditorIK");
#pragma pack(pop)
