// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:39 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Runtime.ConstrainedExecution
namespace System::Runtime::ConstrainedExecution {
  // Autogenerated type: System.Runtime.ConstrainedExecution.CriticalFinalizerObject
  class CriticalFinalizerObject : public ::Il2CppObject {
    public:
    // protected System.Void .ctor()
    // Offset: 0x11509A4
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static CriticalFinalizerObject* New_ctor();
    // protected override System.Void Finalize()
    // Offset: 0x11509AC
    // Implemented from: System.Object
    // Base method: System.Void Object::Finalize()
    void Finalize();
  }; // System.Runtime.ConstrainedExecution.CriticalFinalizerObject
}
DEFINE_IL2CPP_ARG_TYPE(System::Runtime::ConstrainedExecution::CriticalFinalizerObject*, "System.Runtime.ConstrainedExecution", "CriticalFinalizerObject");
#pragma pack(pop)
