// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:24 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Microsoft::Win32
namespace Microsoft::Win32 {
}
// Completed forward declares
// Type namespace: Microsoft.Win32
namespace Microsoft::Win32 {
  // Autogenerated type: Microsoft.Win32.UnsafeNativeMethods
  class UnsafeNativeMethods : public ::Il2CppObject {
    public:
    // Nested type: Microsoft::Win32::UnsafeNativeMethods::ManifestEtw
    class ManifestEtw;
  }; // Microsoft.Win32.UnsafeNativeMethods
}
DEFINE_IL2CPP_ARG_TYPE(Microsoft::Win32::UnsafeNativeMethods*, "Microsoft.Win32", "UnsafeNativeMethods");
#pragma pack(pop)
