// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:19 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.Events.UnityEvent`1
#include "UnityEngine/Events/UnityEvent_1.hpp"
// Including type: TMPro.FloatTween
#include "TMPro/FloatTween.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: TMPro
namespace TMPro {
  // Autogenerated type: TMPro.FloatTween/FloatTweenCallback
  class FloatTween::FloatTweenCallback : public UnityEngine::Events::UnityEvent_1<float> {
    public:
    // public System.Void .ctor()
    // Offset: 0xB64D54
    // Implemented from: UnityEngine.Events.UnityEvent`1
    // Base method: System.Void UnityEvent`1::.ctor()
    // Base method: System.Void UnityEventBase::.ctor()
    // Base method: System.Void Object::.ctor()
    static FloatTween::FloatTweenCallback* New_ctor();
  }; // TMPro.FloatTween/FloatTweenCallback
}
DEFINE_IL2CPP_ARG_TYPE(TMPro::FloatTween::FloatTweenCallback*, "TMPro", "FloatTween/FloatTweenCallback");
#pragma pack(pop)
