// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:19 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
// Including type: TMPro.TMP_InputField
#include "TMPro/TMP_InputField.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: TMPro
namespace TMPro {
  // Autogenerated type: TMPro.TMP_InputField/EditState
  struct TMP_InputField::EditState : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public TMPro.TMP_InputField/EditState Continue
    static constexpr const int Continue = 0;
    // Get static field: static public TMPro.TMP_InputField/EditState Continue
    static TMPro::TMP_InputField::EditState _get_Continue();
    // Set static field: static public TMPro.TMP_InputField/EditState Continue
    static void _set_Continue(TMPro::TMP_InputField::EditState value);
    // static field const value: static public TMPro.TMP_InputField/EditState Finish
    static constexpr const int Finish = 1;
    // Get static field: static public TMPro.TMP_InputField/EditState Finish
    static TMPro::TMP_InputField::EditState _get_Finish();
    // Set static field: static public TMPro.TMP_InputField/EditState Finish
    static void _set_Finish(TMPro::TMP_InputField::EditState value);
    // Creating value type constructor for type: EditState
    EditState(int value_ = {}) : value{value_} {}
  }; // TMPro.TMP_InputField/EditState
}
DEFINE_IL2CPP_ARG_TYPE(TMPro::TMP_InputField::EditState, "TMPro", "TMP_InputField/EditState");
#pragma pack(pop)
