// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:13 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.IDisposable
#include "System/IDisposable.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.ComponentModel.Design
namespace System::ComponentModel::Design {
  // Autogenerated type: System.ComponentModel.Design.IDesigner
  class IDesigner : public System::IDisposable {
  }; // System.ComponentModel.Design.IDesigner
}
DEFINE_IL2CPP_ARG_TYPE(System::ComponentModel::Design::IDesigner*, "System.ComponentModel.Design", "IDesigner");
#pragma pack(pop)
