// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:32 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.Rendering
namespace UnityEngine::Rendering {
  // Autogenerated type: UnityEngine.Rendering.OnDemandRendering
  class OnDemandRendering : public ::Il2CppObject {
    public:
    // Get static field: static private System.Int32 m_RenderFrameInterval
    static int _get_m_RenderFrameInterval();
    // Set static field: static private System.Int32 m_RenderFrameInterval
    static void _set_m_RenderFrameInterval(int value);
    // static public System.Int32 get_renderFrameInterval()
    // Offset: 0x1372B6C
    static int get_renderFrameInterval();
    // static System.Void GetRenderFrameInterval(System.Int32 frameInterval)
    // Offset: 0x1372BD4
    static void GetRenderFrameInterval(int& frameInterval);
    // static private System.Void .cctor()
    // Offset: 0x1372C3C
    static void _cctor();
  }; // UnityEngine.Rendering.OnDemandRendering
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::Rendering::OnDemandRendering*, "UnityEngine.Rendering", "OnDemandRendering");
#pragma pack(pop)
