// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:32 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.Behaviour
#include "UnityEngine/Behaviour.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.Rendering
namespace UnityEngine::Rendering {
  // Autogenerated type: UnityEngine.Rendering.SortingGroup
  class SortingGroup : public UnityEngine::Behaviour {
  }; // UnityEngine.Rendering.SortingGroup
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::Rendering::SortingGroup*, "UnityEngine.Rendering", "SortingGroup");
#pragma pack(pop)
