// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:01 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: Oculus.Platform.Message`1
#include "Oculus/Platform/Message_1.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Oculus::Platform::Models
namespace Oculus::Platform::Models {
  // Forward declaring type: UserList
  class UserList;
}
// Forward declaring namespace: System
namespace System {
  // Skipping declaration: IntPtr because it is already included!
}
// Completed forward declares
// Type namespace: Oculus.Platform
namespace Oculus::Platform {
  // Autogenerated type: Oculus.Platform.MessageWithUserList
  class MessageWithUserList : public Oculus::Platform::Message_1<Oculus::Platform::Models::UserList*> {
    public:
    // protected Oculus.Platform.Models.UserList GetDataFromMessage(System.IntPtr c_message)
    // Offset: 0xE92B24
    Oculus::Platform::Models::UserList* GetDataFromMessage(System::IntPtr c_message);
    // public System.Void .ctor(System.IntPtr c_message)
    // Offset: 0xE89040
    // Implemented from: Oculus.Platform.Message`1
    // Base method: System.Void Message`1::.ctor(System.IntPtr c_message)
    // Base method: System.Void Message::.ctor(System.IntPtr c_message)
    static MessageWithUserList* New_ctor(System::IntPtr c_message);
    // public override Oculus.Platform.Models.UserList GetUserList()
    // Offset: 0xE92AE0
    // Implemented from: Oculus.Platform.Message
    // Base method: Oculus.Platform.Models.UserList Message::GetUserList()
    Oculus::Platform::Models::UserList* GetUserList();
  }; // Oculus.Platform.MessageWithUserList
}
DEFINE_IL2CPP_ARG_TYPE(Oculus::Platform::MessageWithUserList*, "Oculus.Platform", "MessageWithUserList");
#pragma pack(pop)
