// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:18 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Exception
#include "System/Exception.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.ProBuilder.KdTree
namespace UnityEngine::ProBuilder::KdTree {
  // Autogenerated type: UnityEngine.ProBuilder.KdTree.DuplicateNodeError
  class DuplicateNodeError : public System::Exception {
    public:
    // public System.Void .ctor()
    // Offset: 0x1967828
    // Implemented from: System.Exception
    // Base method: System.Void Exception::.ctor()
    // Base method: System.Void Object::.ctor()
    static DuplicateNodeError* New_ctor();
  }; // UnityEngine.ProBuilder.KdTree.DuplicateNodeError
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::ProBuilder::KdTree::DuplicateNodeError*, "UnityEngine.ProBuilder.KdTree", "DuplicateNodeError");
#pragma pack(pop)
