// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:18 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Collections::Generic
namespace System::Collections::Generic {
  // Forward declaring type: List`1<T>
  template<typename T>
  class List_1;
}
// Completed forward declares
// Type namespace: UnityEngine.ProBuilder.KdTree
namespace UnityEngine::ProBuilder::KdTree {
  // Autogenerated type: UnityEngine.ProBuilder.KdTree.KdTreeNode`2
  template<typename TKey, typename TValue>
  class KdTreeNode_2 : public ::Il2CppObject {
    public:
    // public TKey[] Point
    // Offset: 0x0
    ::Array<TKey>* Point;
    // public TValue Value
    // Offset: 0x0
    TValue Value;
    // public System.Collections.Generic.List`1<TValue> Duplicates
    // Offset: 0x0
    System::Collections::Generic::List_1<TValue>* Duplicates;
    // UnityEngine.ProBuilder.KdTree.KdTreeNode`2<TKey,TValue> LeftChild
    // Offset: 0x0
    UnityEngine::ProBuilder::KdTree::KdTreeNode_2<TKey, TValue>* LeftChild;
    // UnityEngine.ProBuilder.KdTree.KdTreeNode`2<TKey,TValue> RightChild
    // Offset: 0x0
    UnityEngine::ProBuilder::KdTree::KdTreeNode_2<TKey, TValue>* RightChild;
    // public System.Void .ctor(TKey[] point, TValue value)
    // Offset: 0x116F148
    static KdTreeNode_2<TKey, TValue>* New_ctor(::Array<TKey>* point, TValue value) {
      return (KdTreeNode_2<TKey, TValue>*)CRASH_UNLESS(il2cpp_utils::New(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<KdTreeNode_2<TKey, TValue>*>::get(), point, value));
    }
    // UnityEngine.ProBuilder.KdTree.KdTreeNode`2<TKey,TValue> get_Item(System.Int32 compare)
    // Offset: 0x116F1A0
    UnityEngine::ProBuilder::KdTree::KdTreeNode_2<TKey, TValue>* get_Item(int compare) {
      return CRASH_UNLESS((il2cpp_utils::RunMethod<UnityEngine::ProBuilder::KdTree::KdTreeNode_2<TKey, TValue>*>(this, "get_Item", compare)));
    }
    // System.Void set_Item(System.Int32 compare, UnityEngine.ProBuilder.KdTree.KdTreeNode`2<TKey,TValue> value)
    // Offset: 0x116F1B8
    void set_Item(int compare, UnityEngine::ProBuilder::KdTree::KdTreeNode_2<TKey, TValue>* value) {
      CRASH_UNLESS(il2cpp_utils::RunMethod(this, "set_Item", compare, value));
    }
    // public System.Void AddDuplicate(TValue value)
    // Offset: 0x116F1D8
    void AddDuplicate(TValue value) {
      CRASH_UNLESS(il2cpp_utils::RunMethod(this, "AddDuplicate", value));
    }
    // public System.Void .ctor()
    // Offset: 0x116F130
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static KdTreeNode_2<TKey, TValue>* New_ctor() {
      return (KdTreeNode_2<TKey, TValue>*)CRASH_UNLESS(il2cpp_utils::New(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<KdTreeNode_2<TKey, TValue>*>::get()));
    }
    // public override System.String ToString()
    // Offset: 0x116F298
    // Implemented from: System.Object
    // Base method: System.String Object::ToString()
    ::Il2CppString* ToString() {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<::Il2CppString*>(this, "ToString"));
    }
  }; // UnityEngine.ProBuilder.KdTree.KdTreeNode`2
}
DEFINE_IL2CPP_ARG_TYPE_GENERIC_CLASS(UnityEngine::ProBuilder::KdTree::KdTreeNode_2, "UnityEngine.ProBuilder.KdTree", "KdTreeNode`2");
#pragma pack(pop)
