// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:18 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: UnityEngine::ProBuilder::KdTree
namespace UnityEngine::ProBuilder::KdTree {
  // Forward declaring type: PriorityQueue`2<TPriority, TItem>
  template<typename TPriority, typename TItem>
  class PriorityQueue_2;
  // Forward declaring type: ITypeMath`1<T>
  template<typename T>
  class ITypeMath_1;
}
// Completed forward declares
// Type namespace: UnityEngine.ProBuilder.KdTree
namespace UnityEngine::ProBuilder::KdTree {
  // Autogenerated type: UnityEngine.ProBuilder.KdTree.NearestNeighbourList`2
  template<typename TItem, typename TDistance>
  class NearestNeighbourList_2 : public ::Il2CppObject {
    public:
    // private UnityEngine.ProBuilder.KdTree.PriorityQueue`2<TItem,TDistance> queue
    // Offset: 0x0
    UnityEngine::ProBuilder::KdTree::PriorityQueue_2<TItem, TDistance>* queue;
    // private UnityEngine.ProBuilder.KdTree.ITypeMath`1<TDistance> distanceMath
    // Offset: 0x0
    UnityEngine::ProBuilder::KdTree::ITypeMath_1<TDistance>* distanceMath;
    // private System.Int32 maxCapacity
    // Offset: 0x0
    int maxCapacity;
    // public System.Void .ctor(System.Int32 maxCapacity, UnityEngine.ProBuilder.KdTree.ITypeMath`1<TDistance> distanceMath)
    // Offset: 0x11722D4
    static NearestNeighbourList_2<TItem, TDistance>* New_ctor(int maxCapacity, UnityEngine::ProBuilder::KdTree::ITypeMath_1<TDistance>* distanceMath) {
      return (NearestNeighbourList_2<TItem, TDistance>*)CRASH_UNLESS(il2cpp_utils::New(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<NearestNeighbourList_2<TItem, TDistance>*>::get(), maxCapacity, distanceMath));
    }
    // public System.Int32 get_MaxCapacity()
    // Offset: 0x1172380
    int get_MaxCapacity() {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<int>(this, "get_MaxCapacity"));
    }
    // public System.Int32 get_Count()
    // Offset: 0x1172388
    int get_Count() {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<int>(this, "get_Count"));
    }
    // public System.Boolean Add(TItem item, TDistance distance)
    // Offset: 0x11723B0
    bool Add(TItem item, TDistance distance) {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<bool>(this, "Add", item, distance));
    }
    // public TDistance GetFurtherestDistance()
    // Offset: 0x1172518
    TDistance GetFurtherestDistance() {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<TDistance>(this, "GetFurtherestDistance"));
    }
    // public TItem RemoveFurtherest()
    // Offset: 0x11725DC
    TItem RemoveFurtherest() {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<TItem>(this, "RemoveFurtherest"));
    }
    // public System.Boolean get_IsCapacityReached()
    // Offset: 0x1172604
    bool get_IsCapacityReached() {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<bool>(this, "get_IsCapacityReached"));
    }
  }; // UnityEngine.ProBuilder.KdTree.NearestNeighbourList`2
}
DEFINE_IL2CPP_ARG_TYPE_GENERIC_CLASS(UnityEngine::ProBuilder::KdTree::NearestNeighbourList_2, "UnityEngine.ProBuilder.KdTree", "NearestNeighbourList`2");
#pragma pack(pop)
