// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:45 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: Zenject.ConditionCopyNonLazyBinder
#include "Zenject/ConditionCopyNonLazyBinder.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Zenject
namespace Zenject {
  // Forward declaring type: BindingCondition
  class BindingCondition;
  // Forward declaring type: InjectContext
  class InjectContext;
}
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.ConditionCopyNonLazyBinder/<>c__5`1
  template<typename T>
  class ConditionCopyNonLazyBinder::$$c__5_1 : public ::Il2CppObject {
    public:
    // Autogenerated static field getter
    // Get static field: static public readonly Zenject.ConditionCopyNonLazyBinder/<>c__5`1<T> <>9
    static Zenject::ConditionCopyNonLazyBinder::$$c__5_1<T>* _get_$$9() {
      return CRASH_UNLESS((il2cpp_utils::GetFieldValue<Zenject::ConditionCopyNonLazyBinder::$$c__5_1<T>*>(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ConditionCopyNonLazyBinder::$$c__5_1<T>*>::get(), "<>9")));
    }
    // Autogenerated static field setter
    // Set static field: static public readonly Zenject.ConditionCopyNonLazyBinder/<>c__5`1<T> <>9
    static void _set_$$9(Zenject::ConditionCopyNonLazyBinder::$$c__5_1<T>* value) {
      CRASH_UNLESS(il2cpp_utils::SetFieldValue(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ConditionCopyNonLazyBinder::$$c__5_1<T>*>::get(), "<>9", value));
    }
    // Autogenerated static field getter
    // Get static field: static public Zenject.BindingCondition <>9__5_0
    static Zenject::BindingCondition* _get_$$9__5_0() {
      return CRASH_UNLESS((il2cpp_utils::GetFieldValue<Zenject::BindingCondition*>(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ConditionCopyNonLazyBinder::$$c__5_1<T>*>::get(), "<>9__5_0")));
    }
    // Autogenerated static field setter
    // Set static field: static public Zenject.BindingCondition <>9__5_0
    static void _set_$$9__5_0(Zenject::BindingCondition* value) {
      CRASH_UNLESS(il2cpp_utils::SetFieldValue(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ConditionCopyNonLazyBinder::$$c__5_1<T>*>::get(), "<>9__5_0", value));
    }
    // static private System.Void .cctor()
    // Offset: 0x117C5F8
    static void _cctor() {
      CRASH_UNLESS(il2cpp_utils::RunMethod(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ConditionCopyNonLazyBinder::$$c__5_1<T>*>::get(), ".cctor"));
    }
    // System.Boolean <WhenNotInjectedInto>b__5_0(Zenject.InjectContext r)
    // Offset: 0x117C6EC
    bool $WhenNotInjectedInto$b__5_0(Zenject::InjectContext* r) {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<bool>(this, "<WhenNotInjectedInto>b__5_0", r));
    }
    // public System.Void .ctor()
    // Offset: 0x117C6D4
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static ConditionCopyNonLazyBinder::$$c__5_1<T>* New_ctor() {
      return (ConditionCopyNonLazyBinder::$$c__5_1<T>*)CRASH_UNLESS(il2cpp_utils::New(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ConditionCopyNonLazyBinder::$$c__5_1<T>*>::get()));
    }
  }; // Zenject.ConditionCopyNonLazyBinder/<>c__5`1
}
DEFINE_IL2CPP_ARG_TYPE_GENERIC_CLASS(Zenject::ConditionCopyNonLazyBinder::$$c__5_1, "Zenject", "ConditionCopyNonLazyBinder/<>c__5`1");
#pragma pack(pop)
