// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:43 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.IPoolable`2
  template<typename TParam1, typename TParam2>
  class IPoolable_2 {
    public:
    // public System.Void OnDespawned()
    // Offset: 0xFFFFFFFF
    void OnDespawned() {
      CRASH_UNLESS(il2cpp_utils::RunMethod(this, "OnDespawned"));
    }
    // public System.Void OnSpawned(TParam1 p1, TParam2 p2)
    // Offset: 0xFFFFFFFF
    void OnSpawned(TParam1 p1, TParam2 p2) {
      CRASH_UNLESS(il2cpp_utils::RunMethod(this, "OnSpawned", p1, p2));
    }
  }; // Zenject.IPoolable`2
}
DEFINE_IL2CPP_ARG_TYPE_GENERIC_CLASS(Zenject::IPoolable_2, "Zenject", "IPoolable`2");
#pragma pack(pop)
