// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:49 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: Zenject.ScriptableObjectInstallerBase
#include "Zenject/ScriptableObjectInstallerBase.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Zenject
namespace Zenject {
  // Forward declaring type: ScriptableObjectInstaller`2<TDerived, TParam1>
  template<typename TDerived, typename TParam1>
  class ScriptableObjectInstaller_2;
  // Forward declaring type: DiContainer
  class DiContainer;
}
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.ScriptableObjectInstaller`2
  template<typename TDerived, typename TParam1>
  class ScriptableObjectInstaller_2 : public Zenject::ScriptableObjectInstallerBase {
    public:
    // static public TDerived InstallFromResource(Zenject.DiContainer container, TParam1 p1)
    // Offset: 0x15DDE14
    static TDerived InstallFromResource(Zenject::DiContainer* container, TParam1 p1) {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<TDerived>(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ScriptableObjectInstaller_2<TDerived, TParam1>*>::get(), "InstallFromResource", container, p1));
    }
    // static public TDerived InstallFromResource(System.String resourcePath, Zenject.DiContainer container, TParam1 p1)
    // Offset: 0x15DDEEC
    static TDerived InstallFromResource(::Il2CppString* resourcePath, Zenject::DiContainer* container, TParam1 p1) {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<TDerived>(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ScriptableObjectInstaller_2<TDerived, TParam1>*>::get(), "InstallFromResource", resourcePath, container, p1));
    }
    // public System.Void .ctor()
    // Offset: 0x15DDFF0
    // Implemented from: Zenject.ScriptableObjectInstallerBase
    // Base method: System.Void ScriptableObjectInstallerBase::.ctor()
    // Base method: System.Void ScriptableObject::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    static ScriptableObjectInstaller_2<TDerived, TParam1>* New_ctor() {
      return (ScriptableObjectInstaller_2<TDerived, TParam1>*)CRASH_UNLESS(il2cpp_utils::New(il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<ScriptableObjectInstaller_2<TDerived, TParam1>*>::get()));
    }
  }; // Zenject.ScriptableObjectInstaller`2
}
DEFINE_IL2CPP_ARG_TYPE_GENERIC_CLASS(Zenject::ScriptableObjectInstaller_2, "Zenject", "ScriptableObjectInstaller`2");
#pragma pack(pop)
