// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:30 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Reflection
namespace System::Reflection {
  // Autogenerated type: System.Reflection.ExceptionHandlingClauseOptions
  struct ExceptionHandlingClauseOptions : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public System.Reflection.ExceptionHandlingClauseOptions Clause
    static constexpr const int Clause = 0;
    // Get static field: static public System.Reflection.ExceptionHandlingClauseOptions Clause
    static System::Reflection::ExceptionHandlingClauseOptions _get_Clause();
    // Set static field: static public System.Reflection.ExceptionHandlingClauseOptions Clause
    static void _set_Clause(System::Reflection::ExceptionHandlingClauseOptions value);
    // static field const value: static public System.Reflection.ExceptionHandlingClauseOptions Filter
    static constexpr const int Filter = 1;
    // Get static field: static public System.Reflection.ExceptionHandlingClauseOptions Filter
    static System::Reflection::ExceptionHandlingClauseOptions _get_Filter();
    // Set static field: static public System.Reflection.ExceptionHandlingClauseOptions Filter
    static void _set_Filter(System::Reflection::ExceptionHandlingClauseOptions value);
    // static field const value: static public System.Reflection.ExceptionHandlingClauseOptions Finally
    static constexpr const int Finally = 2;
    // Get static field: static public System.Reflection.ExceptionHandlingClauseOptions Finally
    static System::Reflection::ExceptionHandlingClauseOptions _get_Finally();
    // Set static field: static public System.Reflection.ExceptionHandlingClauseOptions Finally
    static void _set_Finally(System::Reflection::ExceptionHandlingClauseOptions value);
    // static field const value: static public System.Reflection.ExceptionHandlingClauseOptions Fault
    static constexpr const int Fault = 4;
    // Get static field: static public System.Reflection.ExceptionHandlingClauseOptions Fault
    static System::Reflection::ExceptionHandlingClauseOptions _get_Fault();
    // Set static field: static public System.Reflection.ExceptionHandlingClauseOptions Fault
    static void _set_Fault(System::Reflection::ExceptionHandlingClauseOptions value);
    // Creating value type constructor for type: ExceptionHandlingClauseOptions
    ExceptionHandlingClauseOptions(int value_ = {}) : value{value_} {}
  }; // System.Reflection.ExceptionHandlingClauseOptions
}
DEFINE_IL2CPP_ARG_TYPE(System::Reflection::ExceptionHandlingClauseOptions, "System.Reflection", "ExceptionHandlingClauseOptions");
#pragma pack(pop)
