// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:13 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.IServiceProvider
#include "System/IServiceProvider.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::ComponentModel
namespace System::ComponentModel {
  // Forward declaring type: IContainer
  class IContainer;
}
// Completed forward declares
// Type namespace: System.ComponentModel
namespace System::ComponentModel {
  // Autogenerated type: System.ComponentModel.ISite
  class ISite : public System::IServiceProvider {
    public:
    // public System.ComponentModel.IContainer get_Container()
    // Offset: 0xFFFFFFFF
    System::ComponentModel::IContainer* get_Container();
    // public System.Boolean get_DesignMode()
    // Offset: 0xFFFFFFFF
    bool get_DesignMode();
    // public System.String get_Name()
    // Offset: 0xFFFFFFFF
    ::Il2CppString* get_Name();
  }; // System.ComponentModel.ISite
}
DEFINE_IL2CPP_ARG_TYPE(System::ComponentModel::ISite*, "System.ComponentModel", "ISite");
#pragma pack(pop)
