// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:05 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
// Including type: HMUI.ImageView
#include "HMUI/ImageView.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: HMUI
namespace HMUI {
  // Autogenerated type: HMUI.ImageView/OriginHorizontal
  struct ImageView::OriginHorizontal : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public HMUI.ImageView/OriginHorizontal Left
    static constexpr const int Left = 0;
    // Get static field: static public HMUI.ImageView/OriginHorizontal Left
    static HMUI::ImageView::OriginHorizontal _get_Left();
    // Set static field: static public HMUI.ImageView/OriginHorizontal Left
    static void _set_Left(HMUI::ImageView::OriginHorizontal value);
    // static field const value: static public HMUI.ImageView/OriginHorizontal Right
    static constexpr const int Right = 1;
    // Get static field: static public HMUI.ImageView/OriginHorizontal Right
    static HMUI::ImageView::OriginHorizontal _get_Right();
    // Set static field: static public HMUI.ImageView/OriginHorizontal Right
    static void _set_Right(HMUI::ImageView::OriginHorizontal value);
    // Creating value type constructor for type: OriginHorizontal
    OriginHorizontal(int value_ = {}) : value{value_} {}
  }; // HMUI.ImageView/OriginHorizontal
}
DEFINE_IL2CPP_ARG_TYPE(HMUI::ImageView::OriginHorizontal, "HMUI", "ImageView/OriginHorizontal");
#pragma pack(pop)
