// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:04 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
// Including type: HMUI.SegmentedControlCell
#include "HMUI/SegmentedControlCell.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: HMUI
namespace HMUI {
  // Autogenerated type: HMUI.SegmentedControlCell/TransitionType
  struct SegmentedControlCell::TransitionType : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public HMUI.SegmentedControlCell/TransitionType Instant
    static constexpr const int Instant = 0;
    // Get static field: static public HMUI.SegmentedControlCell/TransitionType Instant
    static HMUI::SegmentedControlCell::TransitionType _get_Instant();
    // Set static field: static public HMUI.SegmentedControlCell/TransitionType Instant
    static void _set_Instant(HMUI::SegmentedControlCell::TransitionType value);
    // static field const value: static public HMUI.SegmentedControlCell/TransitionType Animated
    static constexpr const int Animated = 1;
    // Get static field: static public HMUI.SegmentedControlCell/TransitionType Animated
    static HMUI::SegmentedControlCell::TransitionType _get_Animated();
    // Set static field: static public HMUI.SegmentedControlCell/TransitionType Animated
    static void _set_Animated(HMUI::SegmentedControlCell::TransitionType value);
    // Creating value type constructor for type: TransitionType
    TransitionType(int value_ = {}) : value{value_} {}
  }; // HMUI.SegmentedControlCell/TransitionType
}
DEFINE_IL2CPP_ARG_TYPE(HMUI::SegmentedControlCell::TransitionType, "HMUI", "SegmentedControlCell/TransitionType");
#pragma pack(pop)
