// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:05 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: HMUI
namespace HMUI {
  // Autogenerated type: HMUI.TableViewSelectionType
  struct TableViewSelectionType : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public HMUI.TableViewSelectionType None
    static constexpr const int None = 0;
    // Get static field: static public HMUI.TableViewSelectionType None
    static HMUI::TableViewSelectionType _get_None();
    // Set static field: static public HMUI.TableViewSelectionType None
    static void _set_None(HMUI::TableViewSelectionType value);
    // static field const value: static public HMUI.TableViewSelectionType Single
    static constexpr const int Single = 1;
    // Get static field: static public HMUI.TableViewSelectionType Single
    static HMUI::TableViewSelectionType _get_Single();
    // Set static field: static public HMUI.TableViewSelectionType Single
    static void _set_Single(HMUI::TableViewSelectionType value);
    // static field const value: static public HMUI.TableViewSelectionType Multiple
    static constexpr const int Multiple = 2;
    // Get static field: static public HMUI.TableViewSelectionType Multiple
    static HMUI::TableViewSelectionType _get_Multiple();
    // Set static field: static public HMUI.TableViewSelectionType Multiple
    static void _set_Multiple(HMUI::TableViewSelectionType value);
    // Creating value type constructor for type: TableViewSelectionType
    TableViewSelectionType(int value_ = {}) : value{value_} {}
  }; // HMUI.TableViewSelectionType
}
DEFINE_IL2CPP_ARG_TYPE(HMUI::TableViewSelectionType, "HMUI", "TableViewSelectionType");
#pragma pack(pop)
