// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:42 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.XR
namespace UnityEngine::XR {
  // Autogenerated type: UnityEngine.XR.AvailableTrackingData
  struct AvailableTrackingData : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public UnityEngine.XR.AvailableTrackingData None
    static constexpr const int None = 0;
    // Get static field: static public UnityEngine.XR.AvailableTrackingData None
    static UnityEngine::XR::AvailableTrackingData _get_None();
    // Set static field: static public UnityEngine.XR.AvailableTrackingData None
    static void _set_None(UnityEngine::XR::AvailableTrackingData value);
    // static field const value: static public UnityEngine.XR.AvailableTrackingData PositionAvailable
    static constexpr const int PositionAvailable = 1;
    // Get static field: static public UnityEngine.XR.AvailableTrackingData PositionAvailable
    static UnityEngine::XR::AvailableTrackingData _get_PositionAvailable();
    // Set static field: static public UnityEngine.XR.AvailableTrackingData PositionAvailable
    static void _set_PositionAvailable(UnityEngine::XR::AvailableTrackingData value);
    // static field const value: static public UnityEngine.XR.AvailableTrackingData RotationAvailable
    static constexpr const int RotationAvailable = 2;
    // Get static field: static public UnityEngine.XR.AvailableTrackingData RotationAvailable
    static UnityEngine::XR::AvailableTrackingData _get_RotationAvailable();
    // Set static field: static public UnityEngine.XR.AvailableTrackingData RotationAvailable
    static void _set_RotationAvailable(UnityEngine::XR::AvailableTrackingData value);
    // static field const value: static public UnityEngine.XR.AvailableTrackingData VelocityAvailable
    static constexpr const int VelocityAvailable = 4;
    // Get static field: static public UnityEngine.XR.AvailableTrackingData VelocityAvailable
    static UnityEngine::XR::AvailableTrackingData _get_VelocityAvailable();
    // Set static field: static public UnityEngine.XR.AvailableTrackingData VelocityAvailable
    static void _set_VelocityAvailable(UnityEngine::XR::AvailableTrackingData value);
    // static field const value: static public UnityEngine.XR.AvailableTrackingData AngularVelocityAvailable
    static constexpr const int AngularVelocityAvailable = 8;
    // Get static field: static public UnityEngine.XR.AvailableTrackingData AngularVelocityAvailable
    static UnityEngine::XR::AvailableTrackingData _get_AngularVelocityAvailable();
    // Set static field: static public UnityEngine.XR.AvailableTrackingData AngularVelocityAvailable
    static void _set_AngularVelocityAvailable(UnityEngine::XR::AvailableTrackingData value);
    // static field const value: static public UnityEngine.XR.AvailableTrackingData AccelerationAvailable
    static constexpr const int AccelerationAvailable = 16;
    // Get static field: static public UnityEngine.XR.AvailableTrackingData AccelerationAvailable
    static UnityEngine::XR::AvailableTrackingData _get_AccelerationAvailable();
    // Set static field: static public UnityEngine.XR.AvailableTrackingData AccelerationAvailable
    static void _set_AccelerationAvailable(UnityEngine::XR::AvailableTrackingData value);
    // static field const value: static public UnityEngine.XR.AvailableTrackingData AngularAccelerationAvailable
    static constexpr const int AngularAccelerationAvailable = 32;
    // Get static field: static public UnityEngine.XR.AvailableTrackingData AngularAccelerationAvailable
    static UnityEngine::XR::AvailableTrackingData _get_AngularAccelerationAvailable();
    // Set static field: static public UnityEngine.XR.AvailableTrackingData AngularAccelerationAvailable
    static void _set_AngularAccelerationAvailable(UnityEngine::XR::AvailableTrackingData value);
    // Creating value type constructor for type: AvailableTrackingData
    AvailableTrackingData(int value_ = {}) : value{value_} {}
  }; // UnityEngine.XR.AvailableTrackingData
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::XR::AvailableTrackingData, "UnityEngine.XR", "AvailableTrackingData");
#pragma pack(pop)
