// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:37 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: UnityEngine.TestTools.TestRunner.PlaymodeTestsControllerSettings
#include "UnityEngine/TestTools/TestRunner/PlaymodeTestsControllerSettings.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Func`2<TResult, T>
  template<typename TResult, typename T>
  class Func_2;
}
// Forward declaring namespace: UnityEngine::TestTools::TestRunner::GUI
namespace UnityEngine::TestTools::TestRunner::GUI {
  // Forward declaring type: TestRunnerFilter
  class TestRunnerFilter;
}
// Forward declaring namespace: NUnit::Framework::Interfaces
namespace NUnit::Framework::Interfaces {
  // Forward declaring type: ITestFilter
  class ITestFilter;
}
// Completed forward declares
// Type namespace: UnityEngine.TestTools.TestRunner
namespace UnityEngine::TestTools::TestRunner {
  // Autogenerated type: UnityEngine.TestTools.TestRunner.PlaymodeTestsControllerSettings/<>c
  class PlaymodeTestsControllerSettings::$$c : public ::Il2CppObject {
    public:
    // Get static field: static public readonly UnityEngine.TestTools.TestRunner.PlaymodeTestsControllerSettings/<>c <>9
    static UnityEngine::TestTools::TestRunner::PlaymodeTestsControllerSettings::$$c* _get_$$9();
    // Set static field: static public readonly UnityEngine.TestTools.TestRunner.PlaymodeTestsControllerSettings/<>c <>9
    static void _set_$$9(UnityEngine::TestTools::TestRunner::PlaymodeTestsControllerSettings::$$c* value);
    // Get static field: static public System.Func`2<UnityEngine.TestTools.TestRunner.GUI.TestRunnerFilter,NUnit.Framework.Interfaces.ITestFilter> <>9__5_0
    static System::Func_2<UnityEngine::TestTools::TestRunner::GUI::TestRunnerFilter*, NUnit::Framework::Interfaces::ITestFilter*>* _get_$$9__5_0();
    // Set static field: static public System.Func`2<UnityEngine.TestTools.TestRunner.GUI.TestRunnerFilter,NUnit.Framework.Interfaces.ITestFilter> <>9__5_0
    static void _set_$$9__5_0(System::Func_2<UnityEngine::TestTools::TestRunner::GUI::TestRunnerFilter*, NUnit::Framework::Interfaces::ITestFilter*>* value);
    // static private System.Void .cctor()
    // Offset: 0xE31D00
    static void _cctor();
    // NUnit.Framework.Interfaces.ITestFilter <BuildNUnitFilter>b__5_0(UnityEngine.TestTools.TestRunner.GUI.TestRunnerFilter f)
    // Offset: 0xE31D70
    NUnit::Framework::Interfaces::ITestFilter* $BuildNUnitFilter$b__5_0(UnityEngine::TestTools::TestRunner::GUI::TestRunnerFilter* f);
    // public System.Void .ctor()
    // Offset: 0xE31D68
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static PlaymodeTestsControllerSettings::$$c* New_ctor();
  }; // UnityEngine.TestTools.TestRunner.PlaymodeTestsControllerSettings/<>c
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::TestTools::TestRunner::PlaymodeTestsControllerSettings::$$c*, "UnityEngine.TestTools.TestRunner", "PlaymodeTestsControllerSettings/<>c");
#pragma pack(pop)
