// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:22 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: OnlineServices.API.HTTPAdminLeaderboardsHelper
#include "OnlineServices/API/HTTPAdminLeaderboardsHelper.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: OnlineServices.API
namespace OnlineServices::API {
  // Autogenerated type: OnlineServices.API.HTTPAdminLeaderboardsHelper/ServerStatusResultDto
  class HTTPAdminLeaderboardsHelper::ServerStatusResultDto : public ::Il2CppObject {
    public:
    // public System.Boolean everythingOK
    // Offset: 0x10
    bool everythingOK;
    // public System.Void .ctor()
    // Offset: 0xC2AED0
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static HTTPAdminLeaderboardsHelper::ServerStatusResultDto* New_ctor();
  }; // OnlineServices.API.HTTPAdminLeaderboardsHelper/ServerStatusResultDto
}
DEFINE_IL2CPP_ARG_TYPE(OnlineServices::API::HTTPAdminLeaderboardsHelper::ServerStatusResultDto*, "OnlineServices.API", "HTTPAdminLeaderboardsHelper/ServerStatusResultDto");
#pragma pack(pop)
