// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:00 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: UnityEngine.EventSystems.PointerEventData
#include "UnityEngine/EventSystems/PointerEventData.hpp"
// Including type: UnityEngine.Ray
#include "UnityEngine/Ray.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: UnityEngine::EventSystems
namespace UnityEngine::EventSystems {
  // Forward declaring type: EventSystem
  class EventSystem;
}
// Completed forward declares
// Type namespace: UnityEngine.EventSystems
namespace UnityEngine::EventSystems {
  // Autogenerated type: UnityEngine.EventSystems.OVRPointerEventData
  class OVRPointerEventData : public UnityEngine::EventSystems::PointerEventData {
    public:
    // public UnityEngine.Ray worldSpaceRay
    // Offset: 0x130
    UnityEngine::Ray worldSpaceRay;
    // public UnityEngine.Vector2 swipeStart
    // Offset: 0x148
    UnityEngine::Vector2 swipeStart;
    // public System.Void .ctor(UnityEngine.EventSystems.EventSystem eventSystem)
    // Offset: 0x18E88E8
    // Implemented from: UnityEngine.EventSystems.PointerEventData
    // Base method: System.Void PointerEventData::.ctor(UnityEngine.EventSystems.EventSystem eventSystem)
    // Base method: System.Void BaseEventData::.ctor(UnityEngine.EventSystems.EventSystem eventSystem)
    static OVRPointerEventData* New_ctor(UnityEngine::EventSystems::EventSystem* eventSystem);
    // public override System.String ToString()
    // Offset: 0x18EAA14
    // Implemented from: UnityEngine.EventSystems.PointerEventData
    // Base method: System.String PointerEventData::ToString()
    ::Il2CppString* ToString();
  }; // UnityEngine.EventSystems.OVRPointerEventData
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::EventSystems::OVRPointerEventData*, "UnityEngine.EventSystems", "OVRPointerEventData");
#pragma pack(pop)
