// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:41 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
// Including type: UnityEngine.EventSystems.StandaloneInputModule
#include "UnityEngine/EventSystems/StandaloneInputModule.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.EventSystems
namespace UnityEngine::EventSystems {
  // Autogenerated type: UnityEngine.EventSystems.StandaloneInputModule/InputMode
  struct StandaloneInputModule::InputMode : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public UnityEngine.EventSystems.StandaloneInputModule/InputMode Mouse
    static constexpr const int Mouse = 0;
    // Get static field: static public UnityEngine.EventSystems.StandaloneInputModule/InputMode Mouse
    static UnityEngine::EventSystems::StandaloneInputModule::InputMode _get_Mouse();
    // Set static field: static public UnityEngine.EventSystems.StandaloneInputModule/InputMode Mouse
    static void _set_Mouse(UnityEngine::EventSystems::StandaloneInputModule::InputMode value);
    // static field const value: static public UnityEngine.EventSystems.StandaloneInputModule/InputMode Buttons
    static constexpr const int Buttons = 1;
    // Get static field: static public UnityEngine.EventSystems.StandaloneInputModule/InputMode Buttons
    static UnityEngine::EventSystems::StandaloneInputModule::InputMode _get_Buttons();
    // Set static field: static public UnityEngine.EventSystems.StandaloneInputModule/InputMode Buttons
    static void _set_Buttons(UnityEngine::EventSystems::StandaloneInputModule::InputMode value);
    // Creating value type constructor for type: InputMode
    InputMode(int value_ = {}) : value{value_} {}
  }; // UnityEngine.EventSystems.StandaloneInputModule/InputMode
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::EventSystems::StandaloneInputModule::InputMode, "UnityEngine.EventSystems", "StandaloneInputModule/InputMode");
#pragma pack(pop)
