// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:47 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: NUnit.Framework.Constraints
namespace NUnit::Framework::Constraints {
  // Autogenerated type: NUnit.Framework.Constraints.ConstraintStatus
  struct ConstraintStatus : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public NUnit.Framework.Constraints.ConstraintStatus Unknown
    static constexpr const int Unknown = 0;
    // Get static field: static public NUnit.Framework.Constraints.ConstraintStatus Unknown
    static NUnit::Framework::Constraints::ConstraintStatus _get_Unknown();
    // Set static field: static public NUnit.Framework.Constraints.ConstraintStatus Unknown
    static void _set_Unknown(NUnit::Framework::Constraints::ConstraintStatus value);
    // static field const value: static public NUnit.Framework.Constraints.ConstraintStatus Success
    static constexpr const int Success = 1;
    // Get static field: static public NUnit.Framework.Constraints.ConstraintStatus Success
    static NUnit::Framework::Constraints::ConstraintStatus _get_Success();
    // Set static field: static public NUnit.Framework.Constraints.ConstraintStatus Success
    static void _set_Success(NUnit::Framework::Constraints::ConstraintStatus value);
    // static field const value: static public NUnit.Framework.Constraints.ConstraintStatus Failure
    static constexpr const int Failure = 2;
    // Get static field: static public NUnit.Framework.Constraints.ConstraintStatus Failure
    static NUnit::Framework::Constraints::ConstraintStatus _get_Failure();
    // Set static field: static public NUnit.Framework.Constraints.ConstraintStatus Failure
    static void _set_Failure(NUnit::Framework::Constraints::ConstraintStatus value);
    // static field const value: static public NUnit.Framework.Constraints.ConstraintStatus Error
    static constexpr const int Error = 3;
    // Get static field: static public NUnit.Framework.Constraints.ConstraintStatus Error
    static NUnit::Framework::Constraints::ConstraintStatus _get_Error();
    // Set static field: static public NUnit.Framework.Constraints.ConstraintStatus Error
    static void _set_Error(NUnit::Framework::Constraints::ConstraintStatus value);
    // Creating value type constructor for type: ConstraintStatus
    ConstraintStatus(int value_ = {}) : value{value_} {}
  }; // NUnit.Framework.Constraints.ConstraintStatus
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Framework::Constraints::ConstraintStatus, "NUnit.Framework.Constraints", "ConstraintStatus");
#pragma pack(pop)
