// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:39 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
// Including type: UnityEngine.UI.Image
#include "UnityEngine/UI/Image.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.UI
namespace UnityEngine::UI {
  // Autogenerated type: UnityEngine.UI.Image/OriginHorizontal
  struct Image::OriginHorizontal : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public UnityEngine.UI.Image/OriginHorizontal Left
    static constexpr const int Left = 0;
    // Get static field: static public UnityEngine.UI.Image/OriginHorizontal Left
    static UnityEngine::UI::Image::OriginHorizontal _get_Left();
    // Set static field: static public UnityEngine.UI.Image/OriginHorizontal Left
    static void _set_Left(UnityEngine::UI::Image::OriginHorizontal value);
    // static field const value: static public UnityEngine.UI.Image/OriginHorizontal Right
    static constexpr const int Right = 1;
    // Get static field: static public UnityEngine.UI.Image/OriginHorizontal Right
    static UnityEngine::UI::Image::OriginHorizontal _get_Right();
    // Set static field: static public UnityEngine.UI.Image/OriginHorizontal Right
    static void _set_Right(UnityEngine::UI::Image::OriginHorizontal value);
    // Creating value type constructor for type: OriginHorizontal
    OriginHorizontal(int value_ = {}) : value{value_} {}
  }; // UnityEngine.UI.Image/OriginHorizontal
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::UI::Image::OriginHorizontal, "UnityEngine.UI", "Image/OriginHorizontal");
#pragma pack(pop)
