// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:13 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Diagnostics
namespace System::Diagnostics {
  // Autogenerated type: System.Diagnostics.ProcessInfo
  class ProcessInfo : public ::Il2CppObject {
  }; // System.Diagnostics.ProcessInfo
}
DEFINE_IL2CPP_ARG_TYPE(System::Diagnostics::ProcessInfo*, "System.Diagnostics", "ProcessInfo");
#pragma pack(pop)
