// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:41 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Collections
namespace System::Collections {
  // Autogenerated type: System.Collections.IHashCodeProvider
  class IHashCodeProvider {
    public:
    // public System.Int32 GetHashCode(System.Object obj)
    // Offset: 0xFFFFFFFF
    int GetHashCode(::Il2CppObject* obj);
  }; // System.Collections.IHashCodeProvider
}
DEFINE_IL2CPP_ARG_TYPE(System::Collections::IHashCodeProvider*, "System.Collections", "IHashCodeProvider");
#pragma pack(pop)
