// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:41 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: System.Collections.Stack
#include "System/Collections/Stack.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Collections
namespace System::Collections {
  // Autogenerated type: System.Collections.Stack/StackDebugView
  class Stack::StackDebugView : public ::Il2CppObject {
  }; // System.Collections.Stack/StackDebugView
}
DEFINE_IL2CPP_ARG_TYPE(System::Collections::Stack::StackDebugView*, "System.Collections", "Stack/StackDebugView");
#pragma pack(pop)
