// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:34 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Threading.Tasks
namespace System::Threading::Tasks {
  // Autogenerated type: System.Threading.Tasks.CausalityRelation
  struct CausalityRelation : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public System.Threading.Tasks.CausalityRelation AssignDelegate
    static constexpr const int AssignDelegate = 0;
    // Get static field: static public System.Threading.Tasks.CausalityRelation AssignDelegate
    static System::Threading::Tasks::CausalityRelation _get_AssignDelegate();
    // Set static field: static public System.Threading.Tasks.CausalityRelation AssignDelegate
    static void _set_AssignDelegate(System::Threading::Tasks::CausalityRelation value);
    // static field const value: static public System.Threading.Tasks.CausalityRelation Join
    static constexpr const int Join = 1;
    // Get static field: static public System.Threading.Tasks.CausalityRelation Join
    static System::Threading::Tasks::CausalityRelation _get_Join();
    // Set static field: static public System.Threading.Tasks.CausalityRelation Join
    static void _set_Join(System::Threading::Tasks::CausalityRelation value);
    // static field const value: static public System.Threading.Tasks.CausalityRelation Choice
    static constexpr const int Choice = 2;
    // Get static field: static public System.Threading.Tasks.CausalityRelation Choice
    static System::Threading::Tasks::CausalityRelation _get_Choice();
    // Set static field: static public System.Threading.Tasks.CausalityRelation Choice
    static void _set_Choice(System::Threading::Tasks::CausalityRelation value);
    // static field const value: static public System.Threading.Tasks.CausalityRelation Cancel
    static constexpr const int Cancel = 3;
    // Get static field: static public System.Threading.Tasks.CausalityRelation Cancel
    static System::Threading::Tasks::CausalityRelation _get_Cancel();
    // Set static field: static public System.Threading.Tasks.CausalityRelation Cancel
    static void _set_Cancel(System::Threading::Tasks::CausalityRelation value);
    // static field const value: static public System.Threading.Tasks.CausalityRelation Error
    static constexpr const int Error = 4;
    // Get static field: static public System.Threading.Tasks.CausalityRelation Error
    static System::Threading::Tasks::CausalityRelation _get_Error();
    // Set static field: static public System.Threading.Tasks.CausalityRelation Error
    static void _set_Error(System::Threading::Tasks::CausalityRelation value);
    // Creating value type constructor for type: CausalityRelation
    CausalityRelation(int value_ = {}) : value{value_} {}
  }; // System.Threading.Tasks.CausalityRelation
}
DEFINE_IL2CPP_ARG_TYPE(System::Threading::Tasks::CausalityRelation, "System.Threading.Tasks", "CausalityRelation");
#pragma pack(pop)
