// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:34 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: System.Threading.Tasks.TaskScheduler
#include "System/Threading/Tasks/TaskScheduler.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Threading.Tasks
namespace System::Threading::Tasks {
  // Autogenerated type: System.Threading.Tasks.TaskScheduler/SystemThreadingTasks_TaskSchedulerDebugView
  class TaskScheduler::SystemThreadingTasks_TaskSchedulerDebugView : public ::Il2CppObject {
  }; // System.Threading.Tasks.TaskScheduler/SystemThreadingTasks_TaskSchedulerDebugView
}
DEFINE_IL2CPP_ARG_TYPE(System::Threading::Tasks::TaskScheduler::SystemThreadingTasks_TaskSchedulerDebugView*, "System.Threading.Tasks", "TaskScheduler/SystemThreadingTasks_TaskSchedulerDebugView");
#pragma pack(pop)
