// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:23 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.SystemException
#include "System/SystemException.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Mono.Xml
namespace Mono::Xml {
  // Autogenerated type: Mono.Xml.SmallXmlParserException
  class SmallXmlParserException : public System::SystemException {
    public:
    // private System.Int32 line
    // Offset: 0x88
    int line;
    // private System.Int32 column
    // Offset: 0x8C
    int column;
    // public System.Void .ctor(System.String msg, System.Int32 line, System.Int32 column)
    // Offset: 0x10A3F3C
    static SmallXmlParserException* New_ctor(::Il2CppString* msg, int line, int column);
  }; // Mono.Xml.SmallXmlParserException
}
DEFINE_IL2CPP_ARG_TYPE(Mono::Xml::SmallXmlParserException*, "Mono.Xml", "SmallXmlParserException");
#pragma pack(pop)
