// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:34 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Threading.WaitHandle
#include "System/Threading/WaitHandle.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Threading
namespace System::Threading {
  // Autogenerated type: System.Threading.Mutex
  class Mutex : public System::Threading::WaitHandle {
  }; // System.Threading.Mutex
}
DEFINE_IL2CPP_ARG_TYPE(System::Threading::Mutex*, "System.Threading", "Mutex");
#pragma pack(pop)
