// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:45 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: NUnit.Framework.NUnitAttribute
#include "NUnit/Framework/NUnitAttribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: NUnit.Framework
namespace NUnit::Framework {
  // Autogenerated type: NUnit.Framework.OneTimeTearDownAttribute
  class OneTimeTearDownAttribute : public NUnit::Framework::NUnitAttribute {
  }; // NUnit.Framework.OneTimeTearDownAttribute
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Framework::OneTimeTearDownAttribute*, "NUnit.Framework", "OneTimeTearDownAttribute");
#pragma pack(pop)
