// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:25 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.AudioBehaviour
#include "UnityEngine/AudioBehaviour.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.AudioListener
  class AudioListener : public UnityEngine::AudioBehaviour {
  }; // UnityEngine.AudioListener
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::AudioListener*, "UnityEngine", "AudioListener");
#pragma pack(pop)
