// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:26 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
// Including type: UnityEngine.Camera
#include "UnityEngine/Camera.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.Camera/StereoscopicEye
  struct Camera::StereoscopicEye : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public UnityEngine.Camera/StereoscopicEye Left
    static constexpr const int Left = 0;
    // Get static field: static public UnityEngine.Camera/StereoscopicEye Left
    static UnityEngine::Camera::StereoscopicEye _get_Left();
    // Set static field: static public UnityEngine.Camera/StereoscopicEye Left
    static void _set_Left(UnityEngine::Camera::StereoscopicEye value);
    // static field const value: static public UnityEngine.Camera/StereoscopicEye Right
    static constexpr const int Right = 1;
    // Get static field: static public UnityEngine.Camera/StereoscopicEye Right
    static UnityEngine::Camera::StereoscopicEye _get_Right();
    // Set static field: static public UnityEngine.Camera/StereoscopicEye Right
    static void _set_Right(UnityEngine::Camera::StereoscopicEye value);
    // Creating value type constructor for type: StereoscopicEye
    StereoscopicEye(int value_ = {}) : value{value_} {}
  }; // UnityEngine.Camera/StereoscopicEye
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::Camera::StereoscopicEye, "UnityEngine", "Camera/StereoscopicEye");
#pragma pack(pop)
