// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:35 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.Behaviour
#include "UnityEngine/Behaviour.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.Collider2D
  class Collider2D : public UnityEngine::Behaviour {
  }; // UnityEngine.Collider2D
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::Collider2D*, "UnityEngine", "Collider2D");
#pragma pack(pop)
