// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:26 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: UnityEngine.PropertyName
#include "UnityEngine/PropertyName.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: UnityEngine
namespace UnityEngine {
  // Forward declaring type: Object
  class Object;
  // Forward declaring type: IExposedPropertyTable
  class IExposedPropertyTable;
}
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.ExposedReference`1
  template<typename T>
  struct ExposedReference_1 : public System::ValueType {
    public:
    // public UnityEngine.PropertyName exposedName
    // Offset: 0x0
    UnityEngine::PropertyName exposedName;
    // public UnityEngine.Object defaultValue
    // Offset: 0x0
    UnityEngine::Object* defaultValue;
    // Creating value type constructor for type: ExposedReference_1
    ExposedReference_1(UnityEngine::PropertyName exposedName_ = {}, UnityEngine::Object* defaultValue_ = {}) : exposedName{exposedName_}, defaultValue{defaultValue_} {}
    // public T Resolve(UnityEngine.IExposedPropertyTable resolver)
    // Offset: 0xA3EA88
    T Resolve(UnityEngine::IExposedPropertyTable* resolver) {
      return CRASH_UNLESS(il2cpp_utils::RunMethod<T>(*this, "Resolve", resolver));
    }
  }; // UnityEngine.ExposedReference`1
}
DEFINE_IL2CPP_ARG_TYPE_GENERIC_STRUCT(UnityEngine::ExposedReference_1, "UnityEngine", "ExposedReference`1");
#pragma pack(pop)
