// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:34 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Type
  class Type;
}
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.GUITargetAttribute
  class GUITargetAttribute : public System::Attribute {
    public:
    // System.Int32 displayMask
    // Offset: 0x10
    int displayMask;
    // static private System.Int32 GetGUITargetAttrValue(System.Type klass, System.String methodName)
    // Offset: 0x125EB48
    static int GetGUITargetAttrValue(System::Type* klass, ::Il2CppString* methodName);
  }; // UnityEngine.GUITargetAttribute
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::GUITargetAttribute*, "UnityEngine", "GUITargetAttribute");
#pragma pack(pop)
