// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:28 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.HelpURLAttribute
  class HelpURLAttribute : public System::Attribute {
    public:
    // readonly System.String m_Url
    // Offset: 0x10
    ::Il2CppString* m_Url;
    // public System.Void .ctor(System.String url)
    // Offset: 0x12FA418
    static HelpURLAttribute* New_ctor(::Il2CppString* url);
  }; // UnityEngine.HelpURLAttribute
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::HelpURLAttribute*, "UnityEngine", "HelpURLAttribute");
#pragma pack(pop)
