// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:35 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.ISubsystemDescriptor
#include "UnityEngine/ISubsystemDescriptor.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: IntPtr
  struct IntPtr;
}
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.ISubsystemDescriptorImpl
  class ISubsystemDescriptorImpl : public UnityEngine::ISubsystemDescriptor {
    public:
    // public System.Void set_ptr(System.IntPtr value)
    // Offset: 0xFFFFFFFF
    void UnityEngine_ISubsystemDescriptorImpl_set_ptr(System::IntPtr value);
  }; // UnityEngine.ISubsystemDescriptorImpl
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::ISubsystemDescriptorImpl*, "UnityEngine", "ISubsystemDescriptorImpl");
#pragma pack(pop)
