// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:28 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.ValueType
#include "System/ValueType.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.LayerMask
  struct LayerMask : public System::ValueType {
    public:
    // private System.Int32 m_Mask
    // Offset: 0x0
    int m_Mask;
    // Creating value type constructor for type: LayerMask
    LayerMask(int m_Mask_ = {}) : m_Mask{m_Mask_} {}
    // public System.Int32 get_value()
    // Offset: 0xA423B8
    int get_value();
    // public System.Void set_value(System.Int32 value)
    // Offset: 0xA423C0
    void set_value(int value);
    // static public System.String LayerToName(System.Int32 layer)
    // Offset: 0x12FA5F4
    static ::Il2CppString* LayerToName(int layer);
    // static public System.Int32 NameToLayer(System.String layerName)
    // Offset: 0x12FA634
    static int NameToLayer(::Il2CppString* layerName);
  }; // UnityEngine.LayerMask
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::LayerMask, "UnityEngine", "LayerMask");
#pragma pack(pop)
