// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:28 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Collections::Generic
namespace System::Collections::Generic {
  // Forward declaring type: List`1<T>
  template<typename T>
  class List_1;
}
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Array
  class Array;
}
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.NoAllocHelpers
  class NoAllocHelpers : public ::Il2CppObject {
    public:
    // static public System.Void ResizeList(System.Collections.Generic.List`1<T> list, System.Int32 size)
    // Offset: 0xC4BAE4
    template<class T>
    static void ResizeList(System::Collections::Generic::List_1<T>* list, int size) {
      CRASH_UNLESS(il2cpp_utils::RunGenericMethod("UnityEngine", "NoAllocHelpers", "ResizeList", {il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<T>::get()}, list, size));
    }
    // static public System.Void EnsureListElemCount(System.Collections.Generic.List`1<T> list, System.Int32 count)
    // Offset: 0xC4B9CC
    template<class T>
    static void EnsureListElemCount(System::Collections::Generic::List_1<T>* list, int count) {
      CRASH_UNLESS(il2cpp_utils::RunGenericMethod("UnityEngine", "NoAllocHelpers", "EnsureListElemCount", {il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<T>::get()}, list, count));
    }
    // static public System.Int32 SafeLength(System.Array values)
    // Offset: 0x13FAF10
    static int SafeLength(System::Array* values);
    // static public System.Int32 SafeLength(System.Collections.Generic.List`1<T> values)
    // Offset: 0x11CB528
    template<class T>
    static int SafeLength(System::Collections::Generic::List_1<T>* values) {
      return CRASH_UNLESS(il2cpp_utils::RunGenericMethod<int>("UnityEngine", "NoAllocHelpers", "SafeLength", {il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<T>::get()}, values));
    }
    // static public T[] ExtractArrayFromListT(System.Collections.Generic.List`1<T> list)
    // Offset: 0xD454CC
    template<class T>
    static ::Array<T>* ExtractArrayFromListT(System::Collections::Generic::List_1<T>* list) {
      return CRASH_UNLESS(il2cpp_utils::RunGenericMethod<::Array<T>*>("UnityEngine", "NoAllocHelpers", "ExtractArrayFromListT", {il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<T>::get()}, list));
    }
    // static System.Void Internal_ResizeList(System.Object list, System.Int32 size)
    // Offset: 0x13FE98C
    static void Internal_ResizeList(::Il2CppObject* list, int size);
    // static public System.Array ExtractArrayFromList(System.Object list)
    // Offset: 0x13FB680
    static System::Array* ExtractArrayFromList(::Il2CppObject* list);
  }; // UnityEngine.NoAllocHelpers
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::NoAllocHelpers*, "UnityEngine", "NoAllocHelpers");
#pragma pack(pop)
