// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:35 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.Object
#include "UnityEngine/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.PhysicMaterial
  class PhysicMaterial : public UnityEngine::Object {
  }; // UnityEngine.PhysicMaterial
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::PhysicMaterial*, "UnityEngine", "PhysicMaterial");
#pragma pack(pop)
