// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:35 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: UnityEngine.ISubsystemDescriptor
#include "UnityEngine/ISubsystemDescriptor.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.SubsystemDescriptor
  class SubsystemDescriptor : public ::Il2CppObject, public UnityEngine::ISubsystemDescriptor {
    public:
    // private System.String <id>k__BackingField
    // Offset: 0x10
    ::Il2CppString* id;
    // public System.String get_id()
    // Offset: 0x1961DC8
    ::Il2CppString* get_id();
    // protected System.Void .ctor()
    // Offset: 0x1961DD0
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static SubsystemDescriptor* New_ctor();
  }; // UnityEngine.SubsystemDescriptor
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::SubsystemDescriptor*, "UnityEngine", "SubsystemDescriptor");
#pragma pack(pop)
