// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:16 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.ProBuilder
namespace UnityEngine::ProBuilder {
  // Autogenerated type: UnityEngine.ProBuilder.HandleOrientation
  struct HandleOrientation : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public UnityEngine.ProBuilder.HandleOrientation World
    static constexpr const int World = 0;
    // Get static field: static public UnityEngine.ProBuilder.HandleOrientation World
    static UnityEngine::ProBuilder::HandleOrientation _get_World();
    // Set static field: static public UnityEngine.ProBuilder.HandleOrientation World
    static void _set_World(UnityEngine::ProBuilder::HandleOrientation value);
    // static field const value: static public UnityEngine.ProBuilder.HandleOrientation ActiveObject
    static constexpr const int ActiveObject = 1;
    // Get static field: static public UnityEngine.ProBuilder.HandleOrientation ActiveObject
    static UnityEngine::ProBuilder::HandleOrientation _get_ActiveObject();
    // Set static field: static public UnityEngine.ProBuilder.HandleOrientation ActiveObject
    static void _set_ActiveObject(UnityEngine::ProBuilder::HandleOrientation value);
    // static field const value: static public UnityEngine.ProBuilder.HandleOrientation ActiveElement
    static constexpr const int ActiveElement = 2;
    // Get static field: static public UnityEngine.ProBuilder.HandleOrientation ActiveElement
    static UnityEngine::ProBuilder::HandleOrientation _get_ActiveElement();
    // Set static field: static public UnityEngine.ProBuilder.HandleOrientation ActiveElement
    static void _set_ActiveElement(UnityEngine::ProBuilder::HandleOrientation value);
    // Creating value type constructor for type: HandleOrientation
    HandleOrientation(int value_ = {}) : value{value_} {}
  }; // UnityEngine.ProBuilder.HandleOrientation
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::ProBuilder::HandleOrientation, "UnityEngine.ProBuilder", "HandleOrientation");
#pragma pack(pop)
