// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:16 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
// Including type: UnityEngine.ProBuilder.InternalUtility
#include "UnityEngine/ProBuilder/InternalUtility.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.ProBuilder
namespace UnityEngine::ProBuilder {
  // Autogenerated type: UnityEngine.ProBuilder.InternalUtility/<>c__DisplayClass6_0
  class InternalUtility::$$c__DisplayClass6_0 : public ::Il2CppObject {
    public:
    // public System.String valid
    // Offset: 0x10
    ::Il2CppString* valid;
    // System.Boolean <TryParseColor>b__0(System.Char c)
    // Offset: 0xF87E94
    bool $TryParseColor$b__0(::Il2CppChar c);
    // public System.Void .ctor()
    // Offset: 0xF87BAC
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static InternalUtility::$$c__DisplayClass6_0* New_ctor();
  }; // UnityEngine.ProBuilder.InternalUtility/<>c__DisplayClass6_0
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::ProBuilder::InternalUtility::$$c__DisplayClass6_0*, "UnityEngine.ProBuilder", "InternalUtility/<>c__DisplayClass6_0");
#pragma pack(pop)
