// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:10 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: Valve.VR.CVRRenderModels
#include "Valve/VR/CVRRenderModels.hpp"
// Including type: Valve.VR.IVRRenderModels
#include "Valve/VR/IVRRenderModels.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Valve.VR
namespace Valve::VR {
  // Autogenerated type: Valve.VR.CVRRenderModels/GetComponentStateUnion
  struct CVRRenderModels::GetComponentStateUnion : public System::ValueType {
    public:
    // public Valve.VR.IVRRenderModels/_GetComponentState pGetComponentState
    // Offset: 0x0
    Valve::VR::IVRRenderModels::_GetComponentState* pGetComponentState;
    // public Valve.VR.CVRRenderModels/_GetComponentStatePacked pGetComponentStatePacked
    // Offset: 0x0
    Valve::VR::CVRRenderModels::_GetComponentStatePacked* pGetComponentStatePacked;
    // Creating value type constructor for type: GetComponentStateUnion
    GetComponentStateUnion(Valve::VR::IVRRenderModels::_GetComponentState* pGetComponentState_ = {}, Valve::VR::CVRRenderModels::_GetComponentStatePacked* pGetComponentStatePacked_ = {}) : pGetComponentState{pGetComponentState_}, pGetComponentStatePacked{pGetComponentStatePacked_} {}
  }; // Valve.VR.CVRRenderModels/GetComponentStateUnion
}
DEFINE_IL2CPP_ARG_TYPE(Valve::VR::CVRRenderModels::GetComponentStateUnion, "Valve.VR", "CVRRenderModels/GetComponentStateUnion");
#pragma pack(pop)
