// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:10 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Valve.VR
namespace Valve::VR {
  // Autogenerated type: Valve.VR.EVRNotificationStyle
  struct EVRNotificationStyle : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public Valve.VR.EVRNotificationStyle None
    static constexpr const int None = 0;
    // Get static field: static public Valve.VR.EVRNotificationStyle None
    static Valve::VR::EVRNotificationStyle _get_None();
    // Set static field: static public Valve.VR.EVRNotificationStyle None
    static void _set_None(Valve::VR::EVRNotificationStyle value);
    // static field const value: static public Valve.VR.EVRNotificationStyle Application
    static constexpr const int Application = 100;
    // Get static field: static public Valve.VR.EVRNotificationStyle Application
    static Valve::VR::EVRNotificationStyle _get_Application();
    // Set static field: static public Valve.VR.EVRNotificationStyle Application
    static void _set_Application(Valve::VR::EVRNotificationStyle value);
    // static field const value: static public Valve.VR.EVRNotificationStyle Contact_Disabled
    static constexpr const int Contact_Disabled = 200;
    // Get static field: static public Valve.VR.EVRNotificationStyle Contact_Disabled
    static Valve::VR::EVRNotificationStyle _get_Contact_Disabled();
    // Set static field: static public Valve.VR.EVRNotificationStyle Contact_Disabled
    static void _set_Contact_Disabled(Valve::VR::EVRNotificationStyle value);
    // static field const value: static public Valve.VR.EVRNotificationStyle Contact_Enabled
    static constexpr const int Contact_Enabled = 201;
    // Get static field: static public Valve.VR.EVRNotificationStyle Contact_Enabled
    static Valve::VR::EVRNotificationStyle _get_Contact_Enabled();
    // Set static field: static public Valve.VR.EVRNotificationStyle Contact_Enabled
    static void _set_Contact_Enabled(Valve::VR::EVRNotificationStyle value);
    // static field const value: static public Valve.VR.EVRNotificationStyle Contact_Active
    static constexpr const int Contact_Active = 202;
    // Get static field: static public Valve.VR.EVRNotificationStyle Contact_Active
    static Valve::VR::EVRNotificationStyle _get_Contact_Active();
    // Set static field: static public Valve.VR.EVRNotificationStyle Contact_Active
    static void _set_Contact_Active(Valve::VR::EVRNotificationStyle value);
    // Creating value type constructor for type: EVRNotificationStyle
    EVRNotificationStyle(int value_ = {}) : value{value_} {}
  }; // Valve.VR.EVRNotificationStyle
}
DEFINE_IL2CPP_ARG_TYPE(Valve::VR::EVRNotificationStyle, "Valve.VR", "EVRNotificationStyle");
#pragma pack(pop)
