// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:10 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Valve.VR
namespace Valve::VR {
  // Autogenerated type: Valve.VR.EVROverlayIntersectionMaskPrimitiveType
  struct EVROverlayIntersectionMaskPrimitiveType : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public Valve.VR.EVROverlayIntersectionMaskPrimitiveType OverlayIntersectionPrimitiveType_Rectangle
    static constexpr const int OverlayIntersectionPrimitiveType_Rectangle = 0;
    // Get static field: static public Valve.VR.EVROverlayIntersectionMaskPrimitiveType OverlayIntersectionPrimitiveType_Rectangle
    static Valve::VR::EVROverlayIntersectionMaskPrimitiveType _get_OverlayIntersectionPrimitiveType_Rectangle();
    // Set static field: static public Valve.VR.EVROverlayIntersectionMaskPrimitiveType OverlayIntersectionPrimitiveType_Rectangle
    static void _set_OverlayIntersectionPrimitiveType_Rectangle(Valve::VR::EVROverlayIntersectionMaskPrimitiveType value);
    // static field const value: static public Valve.VR.EVROverlayIntersectionMaskPrimitiveType OverlayIntersectionPrimitiveType_Circle
    static constexpr const int OverlayIntersectionPrimitiveType_Circle = 1;
    // Get static field: static public Valve.VR.EVROverlayIntersectionMaskPrimitiveType OverlayIntersectionPrimitiveType_Circle
    static Valve::VR::EVROverlayIntersectionMaskPrimitiveType _get_OverlayIntersectionPrimitiveType_Circle();
    // Set static field: static public Valve.VR.EVROverlayIntersectionMaskPrimitiveType OverlayIntersectionPrimitiveType_Circle
    static void _set_OverlayIntersectionPrimitiveType_Circle(Valve::VR::EVROverlayIntersectionMaskPrimitiveType value);
    // Creating value type constructor for type: EVROverlayIntersectionMaskPrimitiveType
    EVROverlayIntersectionMaskPrimitiveType(int value_ = {}) : value{value_} {}
  }; // Valve.VR.EVROverlayIntersectionMaskPrimitiveType
}
DEFINE_IL2CPP_ARG_TYPE(Valve::VR::EVROverlayIntersectionMaskPrimitiveType, "Valve.VR", "EVROverlayIntersectionMaskPrimitiveType");
#pragma pack(pop)
