// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:11 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: Valve.VR.IntersectionMaskRectangle_t
#include "Valve/VR/IntersectionMaskRectangle_t.hpp"
// Including type: Valve.VR.IntersectionMaskCircle_t
#include "Valve/VR/IntersectionMaskCircle_t.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Valve.VR
namespace Valve::VR {
  // Autogenerated type: Valve.VR.VROverlayIntersectionMaskPrimitive_Data_t
  struct VROverlayIntersectionMaskPrimitive_Data_t : public System::ValueType {
    public:
    // public Valve.VR.IntersectionMaskRectangle_t m_Rectangle
    // Offset: 0x0
    Valve::VR::IntersectionMaskRectangle_t m_Rectangle;
    // public Valve.VR.IntersectionMaskCircle_t m_Circle
    // Offset: 0x0
    Valve::VR::IntersectionMaskCircle_t m_Circle;
    // Creating value type constructor for type: VROverlayIntersectionMaskPrimitive_Data_t
    VROverlayIntersectionMaskPrimitive_Data_t(Valve::VR::IntersectionMaskRectangle_t m_Rectangle_ = {}, Valve::VR::IntersectionMaskCircle_t m_Circle_ = {}) : m_Rectangle{m_Rectangle_}, m_Circle{m_Circle_} {}
  }; // Valve.VR.VROverlayIntersectionMaskPrimitive_Data_t
}
DEFINE_IL2CPP_ARG_TYPE(Valve::VR::VROverlayIntersectionMaskPrimitive_Data_t, "Valve.VR", "VROverlayIntersectionMaskPrimitive_Data_t");
#pragma pack(pop)
