// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:40 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Runtime.InteropServices
namespace System::Runtime::InteropServices {
  // Autogenerated type: System.Runtime.InteropServices._Thread
  class _Thread {
  }; // System.Runtime.InteropServices._Thread
}
DEFINE_IL2CPP_ARG_TYPE(System::Runtime::InteropServices::_Thread*, "System.Runtime.InteropServices", "_Thread");
#pragma pack(pop)
