// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:25 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Unity.Collections
namespace Unity::Collections {
  // Autogenerated type: Unity.Collections.NativeMatchesParallelForLengthAttribute
  class NativeMatchesParallelForLengthAttribute : public System::Attribute {
  }; // Unity.Collections.NativeMatchesParallelForLengthAttribute
}
DEFINE_IL2CPP_ARG_TYPE(Unity::Collections::NativeMatchesParallelForLengthAttribute*, "Unity.Collections", "NativeMatchesParallelForLengthAttribute");
#pragma pack(pop)
