// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:24 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System
namespace System {
  // Autogenerated type: System.AppContextSwitches
  class AppContextSwitches : public ::Il2CppObject {
    public:
    // Get static field: static public readonly System.Boolean ThrowExceptionIfDisposedCancellationTokenSource
    static bool _get_ThrowExceptionIfDisposedCancellationTokenSource();
    // Set static field: static public readonly System.Boolean ThrowExceptionIfDisposedCancellationTokenSource
    static void _set_ThrowExceptionIfDisposedCancellationTokenSource(bool value);
    // Get static field: static public readonly System.Boolean SetActorAsReferenceWhenCopyingClaimsIdentity
    static bool _get_SetActorAsReferenceWhenCopyingClaimsIdentity();
    // Set static field: static public readonly System.Boolean SetActorAsReferenceWhenCopyingClaimsIdentity
    static void _set_SetActorAsReferenceWhenCopyingClaimsIdentity(bool value);
    // Get static field: static public readonly System.Boolean PreserveEventListnerObjectIdentity
    static bool _get_PreserveEventListnerObjectIdentity();
    // Set static field: static public readonly System.Boolean PreserveEventListnerObjectIdentity
    static void _set_PreserveEventListnerObjectIdentity(bool value);
  }; // System.AppContextSwitches
}
DEFINE_IL2CPP_ARG_TYPE(System::AppContextSwitches*, "System", "AppContextSwitches");
#pragma pack(pop)
