// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:25 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System
namespace System {
  // Autogenerated type: System.FlagsAttribute
  class FlagsAttribute : public System::Attribute {
    public:
    // public System.Void .ctor()
    // Offset: 0xD91EE8
    // Implemented from: System.Attribute
    // Base method: System.Void Attribute::.ctor()
    // Base method: System.Void Object::.ctor()
    static FlagsAttribute* New_ctor();
  }; // System.FlagsAttribute
}
DEFINE_IL2CPP_ARG_TYPE(System::FlagsAttribute*, "System", "FlagsAttribute");
#pragma pack(pop)
