// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:26 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System
namespace System {
  // Autogenerated type: System.ICloneable
  class ICloneable {
    public:
    // public System.Object Clone()
    // Offset: 0xFFFFFFFF
    ::Il2CppObject* Clone();
  }; // System.ICloneable
}
DEFINE_IL2CPP_ARG_TYPE(System::ICloneable*, "System", "ICloneable");
#pragma pack(pop)
