// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:24 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Text
namespace System::Text {
  // Forward declaring type: StringBuilder
  class StringBuilder;
}
// Completed forward declares
// Type namespace: System
namespace System {
  // Autogenerated type: System.ITupleInternal
  class ITupleInternal {
    public:
    // public System.String ToString(System.Text.StringBuilder sb)
    // Offset: 0xFFFFFFFF
    ::Il2CppString* System_ITupleInternal_ToString(System::Text::StringBuilder* sb);
  }; // System.ITupleInternal
}
DEFINE_IL2CPP_ARG_TYPE(System::ITupleInternal*, "System", "ITupleInternal");
#pragma pack(pop)
