// Autogenerated from CppHeaderCreator on 7/24/2020 4:01:14 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System
namespace System {
  // Autogenerated type: System.LocalAppContextSwitches
  class LocalAppContextSwitches : public ::Il2CppObject {
    public:
    // Get static field: static public readonly System.Boolean DontThrowOnInvalidSurrogatePairs
    static bool _get_DontThrowOnInvalidSurrogatePairs();
    // Set static field: static public readonly System.Boolean DontThrowOnInvalidSurrogatePairs
    static void _set_DontThrowOnInvalidSurrogatePairs(bool value);
  }; // System.LocalAppContextSwitches
}
DEFINE_IL2CPP_ARG_TYPE(System::LocalAppContextSwitches*, "System", "LocalAppContextSwitches");
#pragma pack(pop)
