// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:57 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: OVR.OpenVR
namespace OVR::OpenVR {
  // Autogenerated type: OVR.OpenVR.EDeviceActivityLevel
  struct EDeviceActivityLevel : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Unknown
    static constexpr const int k_EDeviceActivityLevel_Unknown = -1;
    // Get static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Unknown
    static OVR::OpenVR::EDeviceActivityLevel _get_k_EDeviceActivityLevel_Unknown();
    // Set static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Unknown
    static void _set_k_EDeviceActivityLevel_Unknown(OVR::OpenVR::EDeviceActivityLevel value);
    // static field const value: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Idle
    static constexpr const int k_EDeviceActivityLevel_Idle = 0;
    // Get static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Idle
    static OVR::OpenVR::EDeviceActivityLevel _get_k_EDeviceActivityLevel_Idle();
    // Set static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Idle
    static void _set_k_EDeviceActivityLevel_Idle(OVR::OpenVR::EDeviceActivityLevel value);
    // static field const value: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_UserInteraction
    static constexpr const int k_EDeviceActivityLevel_UserInteraction = 1;
    // Get static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_UserInteraction
    static OVR::OpenVR::EDeviceActivityLevel _get_k_EDeviceActivityLevel_UserInteraction();
    // Set static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_UserInteraction
    static void _set_k_EDeviceActivityLevel_UserInteraction(OVR::OpenVR::EDeviceActivityLevel value);
    // static field const value: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_UserInteraction_Timeout
    static constexpr const int k_EDeviceActivityLevel_UserInteraction_Timeout = 2;
    // Get static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_UserInteraction_Timeout
    static OVR::OpenVR::EDeviceActivityLevel _get_k_EDeviceActivityLevel_UserInteraction_Timeout();
    // Set static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_UserInteraction_Timeout
    static void _set_k_EDeviceActivityLevel_UserInteraction_Timeout(OVR::OpenVR::EDeviceActivityLevel value);
    // static field const value: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Standby
    static constexpr const int k_EDeviceActivityLevel_Standby = 3;
    // Get static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Standby
    static OVR::OpenVR::EDeviceActivityLevel _get_k_EDeviceActivityLevel_Standby();
    // Set static field: static public OVR.OpenVR.EDeviceActivityLevel k_EDeviceActivityLevel_Standby
    static void _set_k_EDeviceActivityLevel_Standby(OVR::OpenVR::EDeviceActivityLevel value);
    // Creating value type constructor for type: EDeviceActivityLevel
    EDeviceActivityLevel(int value_ = {}) : value{value_} {}
  }; // OVR.OpenVR.EDeviceActivityLevel
}
DEFINE_IL2CPP_ARG_TYPE(OVR::OpenVR::EDeviceActivityLevel, "OVR.OpenVR", "EDeviceActivityLevel");
#pragma pack(pop)
