// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:58 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: OVR.OpenVR
namespace OVR::OpenVR {
  // Autogenerated type: OVR.OpenVR.EVRCompositorTimingMode
  struct EVRCompositorTimingMode : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public OVR.OpenVR.EVRCompositorTimingMode Implicit
    static constexpr const int Implicit = 0;
    // Get static field: static public OVR.OpenVR.EVRCompositorTimingMode Implicit
    static OVR::OpenVR::EVRCompositorTimingMode _get_Implicit();
    // Set static field: static public OVR.OpenVR.EVRCompositorTimingMode Implicit
    static void _set_Implicit(OVR::OpenVR::EVRCompositorTimingMode value);
    // static field const value: static public OVR.OpenVR.EVRCompositorTimingMode Explicit_RuntimePerformsPostPresentHandoff
    static constexpr const int Explicit_RuntimePerformsPostPresentHandoff = 1;
    // Get static field: static public OVR.OpenVR.EVRCompositorTimingMode Explicit_RuntimePerformsPostPresentHandoff
    static OVR::OpenVR::EVRCompositorTimingMode _get_Explicit_RuntimePerformsPostPresentHandoff();
    // Set static field: static public OVR.OpenVR.EVRCompositorTimingMode Explicit_RuntimePerformsPostPresentHandoff
    static void _set_Explicit_RuntimePerformsPostPresentHandoff(OVR::OpenVR::EVRCompositorTimingMode value);
    // static field const value: static public OVR.OpenVR.EVRCompositorTimingMode Explicit_ApplicationPerformsPostPresentHandoff
    static constexpr const int Explicit_ApplicationPerformsPostPresentHandoff = 2;
    // Get static field: static public OVR.OpenVR.EVRCompositorTimingMode Explicit_ApplicationPerformsPostPresentHandoff
    static OVR::OpenVR::EVRCompositorTimingMode _get_Explicit_ApplicationPerformsPostPresentHandoff();
    // Set static field: static public OVR.OpenVR.EVRCompositorTimingMode Explicit_ApplicationPerformsPostPresentHandoff
    static void _set_Explicit_ApplicationPerformsPostPresentHandoff(OVR::OpenVR::EVRCompositorTimingMode value);
    // Creating value type constructor for type: EVRCompositorTimingMode
    EVRCompositorTimingMode(int value_ = {}) : value{value_} {}
  }; // OVR.OpenVR.EVRCompositorTimingMode
}
DEFINE_IL2CPP_ARG_TYPE(OVR::OpenVR::EVRCompositorTimingMode, "OVR.OpenVR", "EVRCompositorTimingMode");
#pragma pack(pop)
