// Autogenerated from CppHeaderCreator on 7/24/2020 4:00:58 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: OVR.OpenVR
namespace OVR::OpenVR {
  // Autogenerated type: OVR.OpenVR.EVRSkeletalMotionRange
  struct EVRSkeletalMotionRange : public System::Enum {
    public:
    // public System.Int32 value__
    // Offset: 0x0
    int value;
    // static field const value: static public OVR.OpenVR.EVRSkeletalMotionRange WithController
    static constexpr const int WithController = 0;
    // Get static field: static public OVR.OpenVR.EVRSkeletalMotionRange WithController
    static OVR::OpenVR::EVRSkeletalMotionRange _get_WithController();
    // Set static field: static public OVR.OpenVR.EVRSkeletalMotionRange WithController
    static void _set_WithController(OVR::OpenVR::EVRSkeletalMotionRange value);
    // static field const value: static public OVR.OpenVR.EVRSkeletalMotionRange WithoutController
    static constexpr const int WithoutController = 1;
    // Get static field: static public OVR.OpenVR.EVRSkeletalMotionRange WithoutController
    static OVR::OpenVR::EVRSkeletalMotionRange _get_WithoutController();
    // Set static field: static public OVR.OpenVR.EVRSkeletalMotionRange WithoutController
    static void _set_WithoutController(OVR::OpenVR::EVRSkeletalMotionRange value);
    // Creating value type constructor for type: EVRSkeletalMotionRange
    EVRSkeletalMotionRange(int value_ = {}) : value{value_} {}
  }; // OVR.OpenVR.EVRSkeletalMotionRange
}
DEFINE_IL2CPP_ARG_TYPE(OVR::OpenVR::EVRSkeletalMotionRange, "OVR.OpenVR", "EVRSkeletalMotionRange");
#pragma pack(pop)
